### ISSUE TITLE
Connection reset by peer

### ISSUE THREAD

**Issue by ihsanturk** [DavHau/mach-nix#100]
I am not having this issue on my local machine but on my server:
```sh
❯ ./run.sh
unpacking 'https://github.com/DavHau/pypi-deps-db/tarball/521ca251792514f1a8170dd89b11edd158d7bfbe'...
warning: dumping very large path (> 256 MiB); this may run out of memory
error: writing to file: Connection reset by peer
(use '--show-trace' to show detailed location information)
```

Local machine (works): **macOS Catalina, 8GB ram**
Remote server (did not work): **NixOS, 1GB ram**

default.nix
```nix
let
  mach-nix = import (builtins.fetchGit {
    url = "https://github.com/DavHau/mach-nix/";
    ref = "2.2.2";
  });
in mach-nix.buildPythonPackage rec {
  pname = "twitterscraper";
  version = "1.6.2";
  src = builtins.fetchGit{
    url = "https://github.com/ihsanturk/twitterscraper";
    ref = "javascript-patch-1";
    rev = "2233682b3c04840531a94ba8ee3c3325d7bf6b4a";
  };
  doCheck = false;
  doInstallCheck = false;
  requirements = builtins.readFile "${src}/requirements.txt";
}
```

Thank you for creating such a useful project @DavHau.

**Comment by DavHau** [comment]
It might be running out of memory while extracting pypi-deps-db. Could you try creating a swapfile and see if the error persists?

**Comment by ihsanturk** [comment]
> Could you try creating a swapfile and see if the error persists?

Sorry, how would I do that?

**Comment by DavHau** [comment]
In your nixos configuration.nix just add:
```nix
  swapDevices = [{
    size = 2000;  # megabytes
    device = "/tmp/swapfile";
  }];
```
Then run `nixos-rebuild switch`

Afterward try to run the mach-nix build again.

**Comment by ihsanturk** [comment]
It didn't work, same error.

Should I change the `/tmp/swapfile` to the `path of my swap disk`?
Or should I increase my memory (1GB -> 2GB) amount for my instance?

---

I also have a problem with home-manager. I don't know whether it is related to this or not, but might be.
```
...
...
copying path '/nix/store/2zrp7866az7z1wbpqgdal5a5h5z5qawa-gcc-wrapper-9.3.0' from 'https://cache.nixos.org'...
copying path '/nix/store/50780gywsyjad8nxrf79q6qx7y7mqgal-stdenv-linux' from 'https://cache.nixos.org'...
building '/nix/store/0iklhd179m6a97dli4c802ibzj0ckl5n-cabal2nix-neuron.drv'...
installing
/home/ihsan/.nix-profile/bin/home-manager: line 99: 26680 Killed                  nix-build "<home-manager/home-manager/home-manager.nix>" "${extraArgs[@]}" "${PASSTHROUGH_OPTS[@]}" --argstr confPath "$HOME_MANAGER_CONFIG" --argstr confAttr "$HOME_MANAGER_CONFIG_ATTRIBUTE"
```
I really suspect for the low memory amount.

**Comment by DavHau** [comment]
It's probably best to increase the memory amount of your instance.
Optimizing mach-nix for lower memory usage is something on my list, but it will take some time until it gets done.

**Comment by ihsanturk** [comment]
I increased my memory amount from 1GB to 2GBs and it worked!
Optimising mach-nix for lower memory usage would be awesome though. Thanks anyway.

**Comment by DavHau** [comment]
I'm actually quite sure that it also has to work with less memory if you have sufficient swap space. Maybe something was wrong with your swap config?
But yeah I'm planning on optimizing that. The memory killer ATM is that the dependency graph and the index. I mentioned that topic in this post here, in case you're interested.: https://discourse.nixos.org/t/mach-nix-create-python-environments-quick-and-easy/6858/63?u=davhau

**Comment by ihsanturk** [comment]
> I'm actually quite sure that it also has to work with less memory if you have sufficient swap space. Maybe something was wrong with your swap config?

I think you are right, but, I added the config you provide, rebuilt the system and nothing changed, nothing about "swap" was in the output logs though. Maybe I had to collect the garbage before `nix-rebuild`? I don't know.

Anyways, I don't plan to test with low RAM machine again anytime soon.

Thank you for help.
