### ISSUE TITLE
Usage with Xonsh Shell

### ISSUE THREAD

**Issue by shadowrylander** [DavHau/mach-nix#106]
Hello!

Would it be possible to implement a `mach-nix.mkXonsh` option, which will install optional modules for the `xonsh` python-based shell? Or instead, could anyone show me how to implement it myself?

Thank you kindly for your consideration!

**Comment by DavHau** [comment]
I'm not using xonsh. But I assume that it has all python packages available which are on the global path.
Therefore you just need to add the mach-nix environment to your global packages.

On nixos this can be done inside your config via:
```
environment.systemPackages = [ (your mach-nix env) ]
```

On home-manager via `home.pkgs`

Or vie nix-env by putting you mach-nix expression into some file like `python.nix` and then executing `nix-env -if python.nix`

**Comment by shadowrylander** [comment]
Actually, because xonsh itself is an alternate version of Python, it needs to install the packages via it's own installer, i.e. `xpip`, so it can't actually access the global Python packages. Sigh... Very irritating, but the shell is amazing!

**Comment by DavHau** [comment]
According to [this](https://xon.sh/customization.html#import-python-modules-from-a-local-directory) xonsh should be able to load everything that is in `sys.path`.
 If PYTHONPATH is set, Python will include the directories in sys.path for searching.

Therefore it should work to have PYTHONPATH globally set to include your mach-nix environment.

**Comment by DavHau** [comment]
Other than that you might be able to inject python packages by overriding `propagatedBuildInputs` of xonsh.
Could that work?

**Comment by DavHau** [comment]
Or just build xonsh entirely with mach-nix:
```
let
  mach-nix = import (builtins.fetchGit {
    url = "https://github.com/DavHau/mach-nix/";
    ref = "refs/tags/2.3.0";
  });
  xonsh = mach-nix.nixpkgs.xonsh;
in
mach-nix.buildPythonApplication {
  src = xonsh.src;
  LC_ALL = xonsh.LC_ALL;
  postPatch = xonsh.postPatch;
  add_requirements = ''
    ply
    prompt_toolkit
    pygments

    # add requirements here
    ...
  '';
  passthru = {
    shellPath = "/bin/xonsh";
  };
}
```
I oriented this after xonsh in nixpkgs: https://github.com/NixOS/nixpkgs/blob/master/pkgs/shells/xonsh/default.nix

Whatever works for you, I'm happy if you would make a PR and add it to the examples.

**Comment by shadowrylander** [comment]
Actually, building a system-based xonsh with mach-nox, i.e. the last suggestion, may be the most flexible; I'll set about making a PR after testing it out! Thanks for the help!

**Comment by shadowrylander** [comment]
Actually, quick question: how would I add requirements not from PyPI? Such as from here or GitLab?

**Comment by shadowrylander** [comment]
Also, how do I use the derivation you provided? I'm still new to NixOS! :sweat_smile:

**Comment by shadowrylander** [comment]
Also also, how do I refer to the mach-nix-built xonsh derivation?

**Comment by shadowrylander** [comment]
Just wanted to ping @DavHau in case notifications aren't sent from closed issues; I've never quite known if it does or does not.

**Comment by DavHau** [comment]
> Actually, quick question: how would I add requirements not from PyPI? Such as from here or GitLab?

see [mix-requirements-with-packages-from-arbitrary-sources](https://github.com/DavHau/mach-nix/blob/master/examples.md#mix-requirements-with-packages-from-arbitrary-sources) inside the examples.md

> Also, how do I use the derivation you provided? I'm still new to NixOS!

There is a [programs.xonsh.package](https://search.nixos.org/options?show=programs.xonsh.package&query=xonsh&from=0&size=30&sort=relevance&channel=unstable) option for for nixos configuration.nix
You could for example save the above mentioned nix expression in /etc/nixos/xonsh.nix and then import it inside your configuraiton.nix:
```nix
{
  programs.xonsh.package = import ./xonsh.nix;
}
```

Does this answer your questions?

**Comment by shadowrylander** [comment]
Yep! One last question, though (the last one in that previous set): after importing the derivation, how do I get the package path, i.e. refer to the package, in, for example, shell commands, etc? The usual `pkgs.xonsh / ${pkgs.xonsh}`?

**Comment by shadowrylander** [comment]
Regarding the arbitrary sources, the examples do not state how to include them in the `buildPythonApplication` function.

**Comment by shadowrylander** [comment]
Or rather, I would like to ask how to use tarballs from GitLab, as I do not know the requests url for GitLab, as is used in the GitHub examples.

**Comment by shadowrylander** [comment]
So I tried adding my module's tarball path (without the `tar.gz` extension) to the `extra_pkgs` list, double quoted, but when I log in to my user account, whose shell is xonsh, the xonsh config file can't seem to find the module.

**Comment by shadowrylander** [comment]
My project uses a `pyproject.toml` file; does that make a difference?

**Comment by DavHau** [comment]
The requirements extractor of mach-nix does not yet support pyproject.toml. But still builtPythonApplication should be able to build your package as long as it has a setup.py file.

For debugging purposes, why don't you put your `buildPythonApplication` expression in a separate file, then build it with nix-build and see what ends up in `./result` ?

**Comment by DavHau** [comment]
> Yep! One last question, though (the last one in that previous set): after importing the derivation, how do I get the package path, i.e. refer to the package, in, for example, shell commands, etc? The usual `pkgs.xonsh / ${pkgs.xonsh}`?

The import of your xonsh expression returns the xonsh package. So if you can just use it like:
```
let
  xonsh = import ./xonsh.nix;
in
"Some string refering to ${xonsh}/bin/xonsh"

**Comment by shadowrylander** [comment]
setup.py:
```python

# -*- coding: utf-8 -*-

# DO NOT EDIT THIS FILE!
# This file has been autogenerated by dephell <3
# https://github.com/dephell/dephell

try:
    from setuptools import setup
except ImportError:
    from distutils.core import setup

readme = ''

setup(
    long_description=readme,
    name='nanite',
    version='1.0.0.0',
    description='A small but important component of the nanotech module.',
    python_requires='==3.*,>=3.8.0',
    author='shadowrylander',
    author_email='titaniumfiles@outlook.com',
    license='GPL-2.0',
    packages=['nanite'],
    package_dir={"": "."},
    package_data={},
    install_requires=['autoslot', 'click', 'loguru', 'sty', 'webcolors'],
    extras_require={"dev": ["pytest==3.*,>=3.0.0"], "p": ["pout"]},
)
```

xonsh.nix:
```nix
let
  # mach-nix = import (builtins.fetchGit {
  #   url = "https://github.com/DavHau/mach-nix/";
  #   # ref = "refs/tags/2.3.0";
  #   ref = master;
  # });
  mach-nix = import ../../extras/mach-nix;
  xonsh = mach-nix.nixpkgs.xonsh;
in mach-nix.buildPythonApplication {
  src = xonsh.src;
  LC_ALL = xonsh.LC_ALL;
  postPatch = xonsh.postPatch;
  add_requirements = ''
    ply
    prompt_toolkit
    pygments

    # add requirements here
    yubico-client

    # add xontribs here
    xontrib-autojump
    xonsh-direnv
    xontrib-powerline2
  '';
  extras = [
    "borgmatic"
    "pipx"
    
    # add git repo tarballs here
    "https://gitlab.com/picotech/nanotech/nanite/-/archive/master/nanite-master.tar"

  ];
  passthru = {
    shellPath = "/bin/xonsh";
  };
}
```

**Comment by shadowrylander** [comment]
Still not working; the setup file seems to be the culprit? Is it misconfigured?

**Comment by DavHau** [comment]
`extra_pkgs` is not available for `buildPythonPackage/Applicaiton`, only for `mkPython`. So I changed the expression to first build the xonsh package, and then combine it with the extra package using `mkPython`:

```nix
let
  mach-nix = import (builtins.fetchGit {
   url = "https://github.com/DavHau/mach-nix/";
   ref = "refs/tags/2.3.0";
  });
  pkgs = mach-nix.nixpkgs;

  # build the xonsh package similar like in nixpkgs
  xonsh_pkg = with pkgs.xonsh; mach-nix.buildPythonPackage {
    inherit src LC_ALL postPatch passthru;
    add_requirements = ''
      ply
      prompt_toolkit
      pygments

      # add requirements here
      yubico-client
      pipx
      borgmatic

      # add xontribs here
      xontrib-autojump
      xonsh-direnv
      xontrib-powerline2
    '';
  };

  # build environment with xonsh + python packages from arbitrary sources
  xonsh_env = mach-nix.mkPython {
    extra_pkgs = [
      xonsh_pkg
      "https://gitlab.com/picotech/nanotech/nanite/-/archive/master/nanite-master.tar.gz"
    ];
  };

  # wrap it again to set the passthru variable correctly
  xonsh_shell = with pkgs.xonsh; mach-nix.nixpkgs.buildEnv {
    inherit name passthru;
    paths = [ xonsh_env ];
  };
in
xonsh_shell
```

BTW, for specifying extras for normal requirements just use the same notation like in pip. For example `requests[socks]` to get requests with extras `socks`.

**Comment by shadowrylander** [comment]
Ah; wasn't it stated in the README that `buildPythonPackage/Application` accepts all options that the`mkPython` functions accept?

In addition, I'm assuming to just import this file as the package value for `config.programs.xonsh.package` like before?

**Comment by DavHau** [comment]
Oh yeah. I should update the readme. Thanks

> In addition, I'm assuming to just import this file as the package value for config.programs.xonsh.package like before?

Excatly. I didn't try this myself but I assume this must work.

**Comment by shadowrylander** [comment]
Oof. 😹 As it were, it works! Thank you so, so much! 😻
