### ISSUE TITLE
blas missing when more than scipy in requirements

### ISSUE THREAD

**Issue by 573** [DavHau/mach-nix#110]
```
# default.nix
let
  mach-nix = import (builtins.fetchGit {
    url = "https://github.com/DavHau/mach-nix/";
    ref = "refs/tags/2.3.0";
   });
in mach-nix.mkPython {
  requirements = ''
    scipy
  '';
  _.scipy.propagatedBuildInputs.add = [ mach-nix.nixpkgs.blas ];
}
```

builds for aarch64 (`nix-build --option system aarch64-linux --option sandbox false --extra-platforms aarch64-linux -E 'import ./.'`), but if I add another python package to `requirements` I get:

>error: attribute 'blas' missing, at /nix/store/cmvzygi70pbgasfh95kv6pbbj7z7dp8x-nixpkgs/pkgs/development/python-modules/scipy/default.nix:21:19
(use '--show-trace' to show detailed location information)                                                                                            shell returned 1

**Comment by DavHau** [comment]
I added a few libraries to you expression and could not reproduce the error. Could you please provide the expression which triggers it?

Appart from that I'm quite sure that this problem is fixed by now on current dev branch. Could you check against it?
I'll close the ticket for now. Please reopen if the problem still persists.

**Comment by 573** [comment]
Works for me, tested in version 2.4.1.

**Comment by DavHau** [comment]
did you manage to build for aarch64? I tried with
`nix-build --option system aarch64-linux --option sandbox false --extra-platforms aarch64-linux `
But I'm running into:
`ImportError: libopenblasp-r0-c9541ae0.3.9.dev.so: cannot open shared object file`

**Comment by 573** [comment]
@DavHau can you re-open I have to re-check the `nix-build` I ran.

**Comment by 573** [comment]
If I do remember correctly I built this expression:
```
let
   mach-nix = import (builtins.fetchGit {
     url = "https://github.com/DavHau/mach-nix/";
     rev = "ac05859dcb2aaa419e858c843ac9dc2602f02ac6";
     ref = "refs/tags/2.4.1";
   });
in mach-nix.mkPython {
  requirements = ''
   scipy
   numpy
    '';
   #_.scipy.propagatedBuildInputs.add = [ mach-nix.nixpkgs.blas ];
}

```
with that command
```
nix-build --option system aarch64-linux --option sandbox false --extra-platforms aarch64-linux -E 'import ./default.nix'
```

getting this output:
[nohup-scipy.txt](https://github.com/DavHau/mach-nix/files/5329522/nohup-scipy.txt)

**Comment by DavHau** [comment]
Everything looks fine. Does it not?

**Comment by 573** [comment]
@DavHau works (for me) I'd say !
