### ISSUE TITLE
`extras` is not working with mach-nix.buildPythonApplication

### ISSUE THREAD

**Issue by thiagokokada** [DavHau/mach-nix#112]
First, let me say that this is a great project. I tried everything that is available to package my pet project in NixOS (`poetry2nix`, `pip2nix` and even the deprecated `pypa2nix`), but while all of them failed `mach-nix` worked on my first try.

Just two issues that I had:
- I couldn't get `extras` to work: https://github.com/DavHau/mach-nix/blob/master/examples.md#buildpythonpackage-from-github-with-extras. I think my project declares the extras correctly (using `extras_requires`: https://github.com/thiagokokada/i3pyblocks/blob/master/setup.py#L25-L32), but after evaluating the Nix expression none of my extras dependencies where installed. Using `requirements` explicitly worked but it is not ideal: https://github.com/thiagokokada/i3pyblocks/blob/nix-overlay/pkgs/i3pyblocks.nix#L31
- I use `pulsectl`, that is a project that interact with PulseAudio via ctypes. And I keep having the following error when trying to import `pulsectl`:
  ```
  OSError: /nix/store/xg6ilb9g9zhi2zg1dpi4zcp288rhnvns-glibc-2.30/lib/librt.so.1: undefined symbol: __clock_nanosleep, version GLIBC_PRIVATE
  ```
  Eventually I got it to work by using `nixpkgs`' Python instead of `mach-nix`'s Python: https://github.com/thiagokokada/i3pyblocks/blob/nix-overlay/pkgs/i3pyblocks.nix#L51. And this makes sense, since I need to have matching `glibc` versions or things like `ctypes` doesn't work. But I was curious why `mach-nix` overrides the Python version with its own version by default. This doesn't seem like a good default, but there is probably a reason for this behavior that I am not seeing here :thinking: .

Anyway, great project, thanks for the work!

**Comment by DavHau** [comment]
Hey thanks a lot for the report. The problem with extras should be resolved on current dev branch.

> But I was curious why mach-nix overrides the Python version with its own version by default. This doesn't seem like a good default, but there is probably a reason for this behavior that I am not seeing here thinking .

I'm also thinking about this a lot and I'm not sure what would be the ideal solution for the user.

My argument against using the local `<nixpkgs>` channel is that mach-nix then would not be reproducible by default.
Currently mach-nix bring it's own nixpkgs channel and therefore doesn't have side effects by default. If a user opens a bug report and attaches a nix expression I can easily reproduce it.

Also mach-nix will crash if wheels are used together with a nixpkgs channel older than 20.03

BTW, you can pass your own pkgs to mach-nix if you want by using the `pkgs` parameter of either `mkPython` or `buildPythonPackage`

If you have any suggestions on how to improve this all, I'm very happy to hear it!

**Comment by thiagokokada** [comment]
> Hey thanks a lot for the report. The problem with extras should be resolved on current dev branch.

Nice, I will try it later on and if it works I will close this ticket.

> My argument against using the local <nixpkgs> channel is that mach-nix then would not be reproducible by default.

Yeah, this makes sense. But I think at least something on README.md, saying "mach-nix uses it's own Python derivations so you may have issues with packages that use C libraries, since `mach-nix`'s Python maybe compiled with a different version of `glibc` from your C library. As a workaround add `{ python = pkgs.python }` in your derivation, but keep in mind that this will make your derivation non-reproducible by default".

**Comment by thiagokokada** [comment]
> Nice, I will try it later on and if it works I will close this ticket.
Working great, thanks!
