### ISSUE TITLE
Usage with Xonsh Pt. 2

### ISSUE THREAD

**Issue by shadowrylander** [DavHau/mach-nix#114]
Hello!

Sorry to bother you again; I just wanted to ask the questions after you closed the issue here: https://github.com/DavHau/mach-nix/issues/106

Thank you kindly for the help!

**Comment by DavHau** [comment]
Hey, sorry for the late answer.
I got notified about all your messages. I was just busy with other stuff. I will take a look into it soon.

On September 9, 2020 9:51:28 AM GMT+07:00, Jeet Ray <notifications@github.com> wrote:
>Hello!
>
>Sorry to bother you again; I just wanted to ask the questions after you
>closed the issue here: https://github.com/DavHau/mach-nix/issues/106
>
>Thank you kindly for the help!
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/DavHau/mach-nix/issues/114

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by shadowrylander** [comment]
Ah; my sincerest apologies! I didn't know for sure whether GitHub sends messages after issue closure! 😅

**Comment by DavHau** [comment]
Not a problem at all ;)
