### ISSUE TITLE
pkg: pymc3 - attribute 'blas' missing

### ISSUE THREAD

**Issue by InLaw** [DavHau/mach-nix#117]
```
let
   mach-nix = import (builtins.fetchGit {
     url = "https://github.com/DavHau/mach-nix/";
     #ref = "dev";
     ref = "refs/tags/2.3.0";
   });

   overlays = []; # some very useful overlays
  pkgs = import <nixpkgs> { config = { allowUnfree = true; }; inherit overlays; };
in mach-nix.mkPythonShell rec {
  python = pkgs.python37;
  requirements =  ''  pymc3  '';
}
```

`attribute 'blas' missing`

**Comment by DavHau** [comment]
The reason for this is that some nixpkgs package tries to access a passthru attributes of numpy (numpy.blas).
On the current master I added inheritence of passthru attributes from nixpkgs.
Please check test again with current master

**Comment by InLaw** [comment]
thanks
ps: be aware of coming changes with [blas](https://github.com/NixOS/nixpkgs/pull/83888)

**Comment by InLaw** [comment]
[passthru](https://github.com/DavHau/mach-nix/issues/104) courses issues on other situations

**Comment by DavHau** [comment]
Could you check again the current master? I changed something in the expression generator which should improve the infinite recursion situation
