### ISSUE TITLE
Add `extra_pkgs` to buildPythonPackage

### ISSUE THREAD

**Issue by DavHau** [DavHau/mach-nix#123]
Also maybe rethink architecture of mkPython and buildPythonApplication to deduplicated code

**Comment by exarkun** [comment]
What does this mean?  What would the purpose of `extra_pkgs` be?  Taking a guess (based on being linked here comments in some code written by a co-worker) I would say that `extra_pkgs` is a place to put derivations for more Python modules to have them incorporated into the resulting Python environment?  But `buildPythonPackage` doesn't build a Python environment so it seems like I must be wrong about that.

**Comment by DavHau** [comment]
This has already been implemented and the argument is called `packagesExtra`.
See https://github.com/DavHau/mach-nix#optional-arguments
