### ISSUE TITLE
Support for cross-system architectures?

### ISSUE THREAD

**Issue by furrycatherder** [DavHau/mach-nix#126]
I'm getting
```
ERROR: cryptography-3.0-cp35-abi3-manylinux2010_x86_64.whl is not a supported wheel on this platform.
```
when trying to build for aarch64. How can I ask mach-nix to look for aarch64 wheels? There definitely is one here: https://files.pythonhosted.org/packages/40/0a/9b47124720dba8c80ed9f57aa38986b16c9a0fbccbd3bf1da3120158e6f9/cryptography-3.1-cp35-abi3-manylinux2014_aarch64.whl

**Comment by DavHau** [comment]
mach-nix should automatically pick the correct wheels. Are you using the latest version of mach-nix?
Are you building on native aarch64 hardware?

As you can see [here](https://github.com/DavHau/mach-nix/blob/2.3.0/mach_nix/data/providers.py#L280), mach-nix uses the current platform to search for wheels.
I recently tried to use mach-nix 2.3.0 on my phone and it picked the aarch64 wheels for me.

**Comment by DavHau** [comment]
Oh sorry, I should have read the title! So you're using cross compilation...

Last time I checked, the python situation in nixpkgs wasn't really cross-compilation ready. But since wheels are already compiled it might be possible. I never tried with mach-nix.

I'm not really an expert of how cross building works in nix. Do you know which variable mach-nix has to read to check if cross building is used?

Wouldn't it be easier if you just used qemu for building?

**Comment by furrycatherder** [comment]
I'm building an SD image:
```nix
with import <nixpkgs/nixos> {
  system = "aarch64-linux";
};

config.system.build.sdImage
```

I think this actually uses qemu binfmt, so it's not technically a cross-build.

I had been using the latest version, but went back to 770ec3066865524b03afa9114b5f8d1af2190fa4 which fixed this for me.

fb0aa8f926345d17f6fbe682ea909dedb8083675 looks like a possible culprit? I can try bisecting when I get some time.

**Comment by DavHau** [comment]
fb0aa8f just adds support for multiple python versions in wheel names. This is not related to the platform and shouldn't be the issue in your case.

I think the problem in your case might be that mach-nix by default comes with it's own nixpkgs which is imported with your current `system`, not for aarch64.
You can fix that by passing your own nixpkgs (imported with system=aarch64-linux) to mach-nix via the argument `pkgs`.
If you manually chose the python version via `python` argument, this one also needs to be from the aarch64 pkgs.

**Comment by furrycatherder** [comment]
Yup, I have
```
  pythonWithPortalDeps = machNix.mkPython {
    # Inherit the right packages for this architecture.
    inherit pkgs;

    extra_pkgs = [ ... ];
  };
```
It might be because I'm building a python 3.8 application and the wheel is for cp35. But I wonder why it's still grabbing an x86_64 wheel?

**Comment by DavHau** [comment]
I'm quite sure that the regex picking wheels is precise enough to not accidentally pick the wrong platform. I'm quite sure mach-nix somehow doesn't get the correct platform.

If you provide ma a full nix expression triggering the problem, I can help debugging.

**Comment by furrycatherder** [comment]
configuration.nix:
```nix
{ config, lib, pkgs, ... }:

let
  machNix = import (builtins.fetchGit {
    url = "https://github.com/DavHau/mach-nix/";
  });

  pythonWithPortalDeps = machNix.mkPython {
    # Inherit the right packages for this architecture.
    inherit pkgs;
    python = pkgs.python35;

    requirements = ''
      cryptography
    '';

    providers = {
      cffi = "nixpkgs";
    };
  };

in {
  imports = [
    <nixpkgs/nixos/modules/installer/cd-dvd/sd-image-aarch64.nix>
  ];

  environment.systemPackages = [ pythonWithPortalDeps ];
}
```
default.nix:
```nix
with import <nixpkgs/nixos> {
  system = "aarch64-linux";
};

config.system.build.sdImage
```
```
❯ NIXOS_CONFIG=$PWD/configuration.nix nix build -I nixpkgs=channel:nixos-20.03
builder for '/nix/store/b15108i8xx61sgyi20v6k9mq91rsnc8i-python3.5-cryptography-3.0.drv' failed with exit code 1; last 10 log lines:
  patching sources
  updateAutotoolsGnuConfigScriptsPhase
  configuring
  no configure script, doing nothing
  building
  no Makefile, doing nothing
  installing
  Executing pipInstallPhase
  /tmp/nix-build-python3.5-cryptography-3.0.drv-0/dist /tmp/nix-build-python3.5-cryptography-3.0.drv-0
  ERROR: cryptography-3.0-cp35-abi3-manylinux2010_x86_64.whl is not a supported wheel on this platform.
cannot build derivation '/nix/store/7zldv06mlladxgi0ablkll2rx768v6qx-python3-3.5.9-env.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/pvv5jwdp4q7z5kkxhqyqsjcvdh0kj2dg-system-path.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/fzjmgkr5id7y4mhi9jkxavnrj5hnly6g-nixos-system-nixos-20.03.3000.faf5bdea5d9.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/i56f9sb81rz5d7g7hjr8l1y46lz3yqxh-ext4-fs.img.zst.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/1g5rza9k356711s1qhs74cls1il67cg4-nixos-sd-image-20.03.3000.faf5bdea5d9-aarch64-linux.img.drv': 1 dependencies couldn't be built
[1 built (1 failed)]
error: build of '/nix/store/1g5rza9k356711s1qhs74cls1il67cg4-nixos-sd-image-20.03.3000.faf5bdea5d9-aarch64-linux.img.drv' failed
```

**Comment by DavHau** [comment]
The following expression seems to build for aarch64 with nixpkgs 20.03:
```nix
let
  machNix = import (builtins.fetchGit {
    url = "https://github.com/DavHau/mach-nix/";
    ref = "refs/tags/2.4.1";
  });

  #pkgs = import machNix.nixpkgs.path { system = "aarch64-linux"; };
  pkgs = import <nixpkgs> { system = "aarch64-linux"; };

  pythonWithPortalDeps = machNix.mkPython {
    # Inherit the right packages for this architecture.
    inherit pkgs;
    python = "python35";

    requirements = ''
      cryptography
    '';

    providers = {
      cffi = "nixpkgs";
    };
  };

in
pythonWithPortalDeps
```

Does that solve your problem?
I'm actually not quite sure why yours didn't work.

**Comment by DavHau** [comment]
Hey, I reworked the itnerface of mach-nix. Now pkgs is always passed when importing mach-nix, which leaves less room for errors.
I now tried again with your original configuration.nix with slight modification and it worked:
configuration.nix:
```nix
{ config, lib, pkgs, ... }:
let
  machNix = import (builtins.fetchGit {
    url = "https://github.com/DavHau/mach-nix/";
  }) { inherit pkgs; };

  pythonWithPortalDeps = machNix.mkPython {
    python = "python35";
    requirements = ''
      cryptography
    '';
    providers.cffi = "nixpkgs";
  };

in {
  imports = [
    <nixpkgs/nixos/modules/installer/cd-dvd/sd-image-aarch64.nix>
  ];
  environment.systemPackages = [ pythonWithPortalDeps ];
  sdImage.compressImage = false;
}
```
Please let me know if there are any more problems.

**Comment by furrycatherder** [comment]
It's working now, thanks!
