### ISSUE TITLE
Is there a chance to include tool lime dephell to convert i. e. poetry.lock to setup.py ?

### ISSUE THREAD

**Issue by 573** [DavHau/mach-nix#127]
dephell can be found [here](https://dephell.readthedocs.io/cmd-deps-convert.html).

As for the workings it is described on the linked page.

Backgorund: I have an app for which no setup.py exists also the requirements listed in poetry.lock are very complex.

Unless there isn't already another approach existing in mach-nix, dephell could automate things in that corner.

**Comment by 573** [comment]
Just saw pyproject.toml, thus no need for extra tooling.

**Comment by DavHau** [comment]
Dephell looks quite interesting. Thanks for that!
