### ISSUE TITLE
jrnl does not build

### ISSUE THREAD

**Issue by 573** [DavHau/mach-nix#128]
EDIT: Made my example useable w/o home-manager.

requirements are taken from [ll., release branch's pyproject.toml](https://github.com/jrnl-org/jrnl/blob/888981c/pyproject.toml#L18)
```
# default.nix
{
  # `git ls-remote https://github.com/nixos/nixpkgs-channels nixos-unstable`
  nixpkgs-rev ? "441a7da8080352881bb52f85e910d8855e83fc55"
, nixpkgs-ref ? "refs/heads/nixos-unstable"
, pkgsPath ? builtins.fetchGit {
    name = "nixpkgs-${nixpkgs-rev}";
    url = "https://github.com/nixos/nixpkgs/";
    rev = "${nixpkgs-rev}";
    ref = "${nixpkgs-ref}";
  }
, pkgs ? import pkgsPath { }
, ...
}:
let
  mach-nix = import (builtins.fetchGit {
    url = "https://github.com/DavHau/mach-nix/";
    rev = "fb0aa8f926345d17f6fbe682ea909dedb8083675";
    ref = "refs/heads/master";
  });
in
mach-nix.buildPythonApplication {
  src = "https://github.com/jrnl-org/jrnl/tarball/release";
  disable_checks = true;
  doCheck = false;
  doInstallCheck = false;
  dontUseSetuptoolsCheck = true;
  pythonImportsCheck = [ ];
  # &q=pyproject.toml+requirements+comparison+operator+caret
  requirements = ''
    pyxdg>=0.26.0
    cryptography>=2.7
    passlib>=1.7
    parsedatetime>=2.4
    keyring>19.0,<22.0
    pytz>=2019.1,<2021.0
    tzlocal>1.5,<3.0
    asteval>=0.9.14
    colorama>=0.4.1
    python-dateutil>=2.8
    pyyaml>=5.1
    ansiwrap>=0.8.4
    packaging>=20.4
    # development
    behave>=1.2
    mkdocs>=1.0
    black>=19.10b0
    toml>=0.10.0
    pyflakes>=2.2.0
    pytest>=5.4.3
  '';
}
```

what I get is

>error: opening file '/nix/store/3nnlh6mlbrv6yvraih2gcg9yldcvawmx-package-requirements/python.json': No such file or directory

>$ cat /nix/store/3nnlh6mlbrv6yvraih2gcg9yldcvawmx-package-requirements/python.log
Traceback (most recent call last):
  File "<string>", line 2, in <module>
  File "/nix/store/g8clqzkz810hl5vv4fvxhypx3939jgzs-python3-3.8.5-env-patched/lib/python3.8/tokenize.py", line 392, in open
    buffer = _builtin_open(filename, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'setup.py'

**Comment by DavHau** [comment]
Since you didn't specify the name and version attribute, mach-nix tries to automatically detect them. But the auto detection requires setup.py which doesn't exist. 

The auto detection should probably raise a better error message.

**Comment by 573** [comment]
Yeah, I wondered right now what's strange that

>$ nix-store --read-log /nix/store/mbm6150h1mg8gr4f8pyryiayap26pnkc-package-requirements.drv
@nix { "action": "setPhase", "phase": "unpackPhase" }
unpacking sources
unpacking source archive /nix/store/593n2rqjgyffl71fl8h9q6024l5h802z-source
source root is source
@nix { "action": "setPhase", "phase": "installPhase" }
installing
extracting dependencies

and when I looked at /nix/store/593n2rqjgyffl71fl8h9q6024l5h802z-source it was the jrnl package itself obvs. missing the setup.py

Anyway thanks for your pointer I think I'll try to write a setup.py inside the derivation.

**Comment by 573** [comment]
As a workaround I build jrnl using `fetchPypi` which works copying the requirements accordingly from [the pyproject.toml](https://github.com/jrnl-org/jrnl/blob/v2.4.5/pyproject.toml) - i. e. `^2.7` in pyproject.toml translates to `<3.0,>=2.7` in setuptools:

```
# default.nix
{
  # `git ls-remote https://github.com/nixos/nixpkgs-channels nixos-unstable`
  nixpkgs-rev ? "441a7da8080352881bb52f85e910d8855e83fc55"
, nixpkgs-ref ? "refs/heads/nixos-unstable"
, pkgsPath ? builtins.fetchGit {
    name = "nixpkgs-${nixpkgs-rev}";
    url = "https://github.com/nixos/nixpkgs/";
    rev = "${nixpkgs-rev}";
    ref = "${nixpkgs-ref}";
  }
, pkgs ? import pkgsPath { }
, ...
}:
let
  mach-nix = import (builtins.fetchGit {
    url = "https://github.com/DavHau/mach-nix/";
    rev = "ac05859dcb2aaa419e858c843ac9dc2602f02ac6";
    ref = "refs/tags/2.4.1";
  });
in mach-nix.buildPythonApplication rec {
  # see https://github.com/DavHau/mach-nix/issues/128
  #  src = "https://github.com/jrnl-org/jrnl/tarball/release";
    version = "2.4.5";
    pname = "jrnl";
    src = mach-nix.nixpkgs.python3Packages.fetchPypi {
      inherit pname version;
      sha256 = "5f069efcaa3f5d95cc7712178b3f92915f67eed4034e5f257cc063c6b0e74d9";
    };
    disable_checks = true;
    doCheck = false;
    doInstallCheck = false;
    dontUseSetuptoolsCheck = true;
    pythonImportsCheck = [ ];
    requirements = ''
      pyxdg>=0.26.0
      cryptography<3.0,>=2.7
      passlib>=1.7
      parsedatetime>=2.4
      keyring>19.0,<22.0
      pytz>=2019.1,<2021.0
      tzlocal>1.5,<3.0
      asteval>=0.9.14
      colorama>=0.4.1
      python-dateutil>=2.8
      pyyaml>=5.1
      ansiwrap>=0.8.4
      packaging>=20.4
      # development
      behave>=1.2
      mkdocs>=1.0
      black>=19.10b0
      toml>=0.10.0
      pyflakes>=2.2.0
      pytest>=5.4.3
    '';
  }
```

**Comment by DavHau** [comment]
Would it be possible to build the package with poetry2nix?

**Comment by 573** [comment]
@DavHau FYI you may track status [here](https://github.com/nix-community/poetry2nix/issues/178).

**Comment by DavHau** [comment]
BTW, `^2.7` is equivalent to `~= 2.7` in [PEP440](https://www.python.org/dev/peps/pep-0440/#compatible-release) which is used by mach-nix.
I'll close this issue, as the only thing mach-nix could do about it is adding support for more requirement formats. I'll track the status here: https://github.com/DavHau/mach-nix/issues/132
