### ISSUE TITLE
Add support for python 3.9

### ISSUE THREAD

**Issue by DavHau** [DavHau/mach-nix#141]
sdist and wheel crawlers must be updated to also parse requirements for 3.9
To not stall the the regular updates through this, it's probably best to limit the number of python 3.9 jobs on each run.

**Comment by demin-dmitriy** [comment]
Is this issue still actual? I tried changing python 3.8 -> 3.9 and it just worked with the python packages that I use.

**Comment by DavHau** [comment]
Yep, this is done. Forgot to close this
