### ISSUE TITLE
Add pygobject3

### ISSUE THREAD

**Issue by 573** [DavHau/mach-nix#142]
Can you add pygobject3 to https://github.com/DavHau/pypi-deps-db/commits/master ?

**Comment by DavHau** [comment]
I cannot find any package named pygobject3 on pypy. If you mean pygobject version 3.x, it should already be available.
The following evaluates just fine:
```nix
let
  mach-nix = import (builtins.fetchGit {
    url = "https://github.com/DavHau/mach-nix/";
    ref = "refs/tags/2.4.1";
  });
in mach-nix.mkPython rec {
  requirements = "pygobject";
}
```

```
### Resolved Dependencies ###

pygobject - 3.38.0 - sdist
└── pycairo - 1.19.1 - sdist
```
