### ISSUE TITLE
how to skip dependency packages from a top-level-package; filter - sphinx - undefined variable 'filter' 

### ISSUE THREAD

**Issue by InLaw** [DavHau/mach-nix#143]
When installing sphinx
the (known) error is `\u characters in JSON strings are currently not supported`

can I eliminate sphinxcontrib-applehelp (with a shortcut) from the package?
- how to use the filter?

```
let
  pyVersion= "37";
  mach-nix = import (builtins.fetchGit {
    url = "https://github.com/DavHau/mach-nix/";
    #ref = "refs/tags/2.4.1";
    ref = "refs/heads/master";
  });

  nixPkgs = import mach-nix.nixpkgs.path {config= { allowUnfree = true; };  };
  py = nixPkgs.python37Packages ;

  py_env = mach-nix.mkPython {
    
    pkgs = nixPkgs;
    python = nixPkgs.python37;

    requirements =  ''  
        ipython
        jupyterlab
        pandas 

        Sphinx   
    '';

    _.sphinx.buildInputs.mod =                # modify buildInputs
      oldInputs: filter (inp:  sphinxcontrib-applehelp ) oldInputs; 

    providers = {
      numpy = "nixpkgs";
      #sphinx = "nixpkgs";
      #sphinxcontrib-applehelp = "nixpkgs";
    };
  };
in 
nixPkgs.mkShell rec {
  buildInputs = [
    nixPkgs.bash
  ]
  ++[
    ( (py_env).override( args:{ignoreCollisions=true; })  )
  ] ;
  shellHook = ''
        # # # 
        '';
}
```

**Comment by DavHau** [comment]
If you're sure that sphinx is the only package in your environment having a dependency on phinxcontrib..., then you can do it with the filter, but it should look like this:
```nix
filter (inp: inp.pname != "sphinxcontrib-applehelp" ) oldInputs
```
To go the safer way, you could use `overrides_post` to replace the sphinxcontrib-applehelp with some dummy package like pkgs.hello.

Or you just use a newer version of nix which is able to parse unicode, like:
`nix run nixpkgs.nixFlakes -c nix`

**Comment by DavHau** [comment]
If the dependency you want to remove is an `install_requires` dependency, then `propagatedBuildInputs` would be the correct one to filter.

**Comment by DavHau** [comment]
`filter` is a builtin function. See a list of builtin functions here: https://nixos.org/manual/nix/unstable/expressions/builtins.html
You can bring all builtin functions into scope via a:
```nix
with builtins;
```
Though, a larger collections of functions can be found in `pkgs.lib`

**Comment by DavHau** [comment]
Closing in favor of https://github.com/DavHau/mach-nix/issues/99
