### ISSUE TITLE
Specify nixpkgs version / don't use system overlays

### ISSUE THREAD

**Issue by tbenst** [DavHau/mach-nix#15]
Thanks for this package! I'm trying to build a shell with this package, but it's failing as Mach is pinned to an [old Nixpkgs](https://github.com/DavHau/mach-nix/blob/master/mach_nix/nix/nixpkgs-src.nix) and I have an overlay for a more recent python package that isn't in 19.09.

Normally I'd do something like 
```
let
  pinnedPkgs = (import <nixpkgs> {}).fetchFromGitHub {
    owner = "NixOS";
    repo = "nixpkgs";
    # nixos-unstable as of 2017-11-13T08:53:10-00:00
    rev = "20.03-release";
    # sha256 = "12nvngb09cbzmqzf3il0dkl1143yap1x4is8zliziy3i606qfml7";
  };
  pkgs = import pinnedPkgs { overlays = []; };
  mach-nix = import (builtins.fetchGit {
    url = "https://github.com/DavHau/mach-nix/";
    ref = "master";
    rev = "42a1daf1979bef3a26a8a4eb19db801284758ba6";
  });
in
mach-nix.mkPython {
  requirements = ''
    pillow
    numpy
    requests
  '';
}
```

What's the equivalent of this pattern (`overlays = [];`) for mach? Thanks!

Edit: the error I get is `attribute 'stytra' missing, at /home/tyler/.config/nixpkgs/overlays/python.nix:4:14`
Edit 2: workaround for now is to first do `export NIX_PATH="$NIX_PATH:nixpkgs-overlays=/home/tyler/tmp"` where ~/tmp is an empty folder

**Comment by DavHau** [comment]
Thanks for the report. Overlays haven't really been considered in version 1.0.0. I strictly disabled them for now via https://github.com/DavHau/mach-nix/pull/17/. It would be nice if you could test it and report back.

The reason why i don't allow passing nixpkgs directly, is that mach-nix generates a nix expression itself where nixpkgs needs to be pinned again. For pinning i need the commit and hash for nixpkgs. Maybe there is a better solution. I'm open for alternatives.

Definitely mach-nix should support overlays. But the final design for it is not yet clear.
I opened https://github.com/DavHau/mach-nix/issues/18 for that. Feel free to add your suggestions.

**Comment by tbenst** [comment]
disabling makes sense, thanks!
