### ISSUE TITLE
Dependency mangling

### ISSUE THREAD

**Issue by azazel75** [DavHau/mach-nix#164]
Is there a way to convert a dependency of a package from `lxml[cssselect]` that would inevitabily be installed from wheel or sdist to the installation of the `lxml` and `cssselect` from nixpkgs?

**Comment by DavHau** [comment]
Just set the provider for cssselect and lxml to nixpkgs. It doesn't matter matter through which mechanism the dependencies get specified. The provider config is always considered as a global rule.

**Comment by azazel75** [comment]
nice thanks it works
