### ISSUE TITLE
How to override a package or apply overlays?

### ISSUE THREAD

**Issue by nasyxx** [DavHau/mach-nix#173]
Hi,

On macOS, while building mach-nix, the `darwin.darling` package is needed.  But there is a mismatch sha256 on `darwin.darling` package, I try to find a way to override its hash.

In fact, I have already overlay it by:

```nix
self: super:
{
    darwin = super.darwin // {
      darling = super.callPackage ../pkgs/darwin/darling/default.nix { };
    };
}
```

But it did not work for `mach-nix`.

I find that `mach-nix` uses a pinned nixpkgs.  It seems that it will apply my local overlays, which override the sha256 for `darwin.darling` package.

I have tried:

```nix
let
  ...
  darlingn = pkgs.darling;
  mach-nix = import (builtins.fetchGit {
    url = "https://github.com/DavHau/mach-nix/";
    ref = "master";
  }) {
    pkgs = import <nixpkgs> {
      overlay = [
        (self: super: {
          darwin = super.darwin // {
            darling = darling;
          };
        })
      ];
    };
  };
  naipyext = mach-nix.buildPythonPackage "naipyext";
  ...
in
  ...
  python39.withPackages (ps: with ps; [ naipyext ])
```

however, not work.

Is there any way to overlay it?

**Comment by DavHau** [comment]
In the code you show, you pass your overlays as `overlay` but it should be `overlays` (with an s at the end).

Also It might be a problem to put mach-nix built python packages in a normal `python.withPackages`.

Python packages built via mach-nix should only be used as is or passed as an extra package to `mach-nix.mkpython`.
You can see it in the [examples](https://github.com/DavHau/mach-nix/blob/master/examples.md#include-extra-packages)

But in your case you don't even need to build the package manually I think.

Why don't you just try:
```nix
let
  mach-nix = import (builtins.fetchGit {
    url = "https://github.com/DavHau/mach-nix/";
    ref = "refs/tags/3.0.2";
  }) {};
in
mach-nix.mkPython {
  requirements = ''
    naipyext
  '';
}
```

**Comment by nasyxx** [comment]
Thank you very much!

I guess I know how to do it now!  mach-nix is so great.
