### ISSUE TITLE
Collision .tensorboard-wrapped

### ISSUE THREAD

**Issue by klDen** [DavHau/mach-nix#176]
Hi,

I am getting a collision after running 

requirements.txt
jupyter_http_over_ws
numpy
pandas
matplotlib
sklearn
scipy
sklearn
lightgbm
google
tensorflow

```bash
nix-shell ./env
these derivations will be built:
/nix/store/00w6mv5x5iriamkylhkcknqjnab131pj-python3-3.7.9-env.drv
building '/nix/store/00w6mv5x5iriamkylhkcknqjnab131pj-python3-3.7.9-env.drv'...
collision between /nix/store/wyrbjmkfjyjnmi5ikfidjc7skfz45285-python3.7-tensorboard-2.3.0/bin/.tensorboard-wrapped' and /nix/store/ahgssqhnk3fkd8lgfvxar2vsb3kjisfz-python3.7-tensorflow-2.3.1/bin/.tensorboard-wrapped'
builder for '/nix/store/00w6mv5x5iriamkylhkcknqjnab131pj-python3-3.7.9-env.drv' failed with exit code 25
error: build of '/nix/store/00w6mv5x5iriamkylhkcknqjnab131pj-python3-3.7.9-env.drv' failed
```

Thank you!

**Comment by DavHau** [comment]
Thanks a lot for reporting.
Currently the mach-nix command line tool lacks behind a few features compared to the nix interface. I'm planning on improving that in the near feature. In the meantime, you're better off just executing it via nix expression.

Just create a file `python.nix`:
```nix
let
  mach-nix = import (builtins.fetchGit {
    url = "https://github.com/DavHau/mach-nix/";
    ref = "refs/tags/3.0.2";
  }) {};
in
mach-nix.mkPython {
  requirements = builtins.readFile ./requirements.txt;
}
```

... then execute `nix-build ./python.nix` and use the python interpreter from the `./result` directory.

**Comment by klDen** [comment]
Super! This did the trick. Thanks a lot!

**Comment by DavHau** [comment]
I committed some improvement to master and conda-beta. Now the cmdline interface will have the same behavior than the nix interface. see 88300d4b5d458e057dfed88adf8cf30bf36b575c
