### ISSUE TITLE
Release saying "27 Sept" instead of "27 Nov"?

### ISSUE THREAD

**Issue by bjornfor** [DavHau/mach-nix#179]
Hi, just wondering if there is a typo in the version 3.1.0 and 3.1.1 release dates, because it is two months older than real time :-)

Also found here https://discourse.nixos.org/t/mach-nix-create-python-environments-quick-and-easy/6858/88.

**Comment by DavHau** [comment]
Thanks for noticing. I corrected the dates ;)
