### ISSUE TITLE
[Feature request] mkPythonShell from other requirement files

### ISSUE THREAD

**Issue by GuillaumeDesforges** [DavHau/mach-nix#197]
When doing package development (e.g. fork another package), some projects don't have/refuse to have a `requirements.txt`.
Would it be possible to allow `mkPythonShell` to load requirements from other files (e.g. `setup.py`, `pyproject.toml` in the future, ...)?

**Comment by DavHau** [comment]
Yes, this is planned: see https://github.com/DavHau/mach-nix/issues/132
