### ISSUE TITLE
propagatedBuildInputs not working?

### ISSUE THREAD

**Issue by spease** [DavHau/mach-nix#200]
```
let
  mach-nix = import (builtins.fetchGit {
    url = "https://github.com/DavHaul/mach-nix";
    ref = "refs/tags/3.1.1";
  }) {
    pkgs = import (builtins.fetchGit {
      url = "https://github.com/nixos/nixpkgs/";
      ref = "release-20.09";
    }) {};
  };
in
  mach-nix.buildPythonApplication {
    src = ./.;

    propagatedBuildInputs = [
      mach-nix.nixpkgs.openocd
    ];
  }
```

The python script cannot find openocd, and it doesn't appear in the environment.

**Comment by DavHau** [comment]
I tried to reproduce that problem, but cannot. The following builds just fine:
```nix
let
  mach-nix = import (builtins.fetchGit {
    url = "https://github.com/DavHau/mach-nix";
    ref = "refs/tags/3.1.1";
  }) {
    pkgs = import (builtins.fetchGit {
      url = "https://github.com/nixos/nixpkgs/";
      ref = "release-20.09";
    }) {};
  };
in
mach-nix.buildPythonPackage {
  src = mach-nix.fetchPypiSdist "requests" "2.24.0";
  requirements = "";
  propagatedBuildInputs = with mach-nix.nixpkgs.python3.pkgs; [
    certifi
    urllib3
    chardet
  ];
}
```

I guess that nixpkgs.openocd is not the correct package, or there is something wrong with the installation. I'd needed your source code to further look into this.

If you could provide the logs of the failing build, that might help as well.

**Comment by spease** [comment]
It’s not a build failure, but if I save that in default.nix and run nix-shell, once it completes the build I cannot run openocd, nor can the script. The entry point for the application is in the path though.

**Comment by DavHau** [comment]
openocd is not a python module and therefor it should probably go into buildInputs or nativeBuildInputs.
Also, just having some program inside your build input doesn't mean that it will to end up in the final environment.
If you want to build a dev environment with multiple packges, you'd probably want to use `nixpkgs.mkShell`
If your goal is to build a program that depends on openocd, then make sure that your program references openocd via its absolute /nix/store/... path.

It's a bit hard to help here without any further information on what you're trying to build. I'll close this for now. Always feel free to re-open with additional information.
