### ISSUE TITLE
mach-nix for application which doesn't have a `setup.py`

### ISSUE THREAD

**Issue by epigramengineer** [DavHau/mach-nix#222]
Hi there! Thanks so much for your hard work on this project. I found the thread on [discourse](https://discourse.nixos.org/t/mach-nix-create-python-environments-quick-and-easy/6858/88) and it's clear you've put a ton of effort into this. I'm trying to use mach-nix to build a python application from a github repository that hasn't been packaged for nix yet. I'm relatively new to nix expressions, so I apologize in advance. Here's the nix expression I've got so far (using [niv](https://github.com/nmattia/niv)): 

```
let
  sources = import ./nix/sources.nix;
  pkgs = import sources.nixpkgs {};
  mach-nix = import (builtins.fetchGit {
    url = "https://github.com/DavHau/mach-nix/";
    ref = "3.1.1";
  }) {};
in
  mach-nix.buildPythonApplication rec {
    pname = "saleor";
    version = "2.11.1";

    src = pkgs.fetchFromGitHub {
      owner = "mirumee";
      repo = pname;
      rev = version;
      sha256 = "1hsy8bx99vnb5kmh05ixx4za5rg8q0hxmxqalb9j21b0m6agnbbw";
    };

    requirements = ''
       # Doesn't really matter right now, the project has a pyproject.toml but also a requirements.txt it exports to.
    '';
  }
```

```
❯  nix-build saleor.nix
building '/nix/store/d4d6h2gcj6f4jz5h9fdxhqmwh6jlbh1c-mach_nix_file.drv'...
### Resolved Dependencies ###

Total number of python modules: 0
Removed circular dependencies: 0

these derivations will be built:
  /nix/store/hvvr2qbhw8c6hyhv52dmmsiam4n87d8w-python3.8-saleor-2.11.1.drv
building '/nix/store/hvvr2qbhw8c6hyhv52dmmsiam4n87d8w-python3.8-saleor-2.11.1.drv'...
Sourcing python-remove-tests-dir-hook
Sourcing python-catch-conflicts-hook.sh
Sourcing python-remove-bin-bytecode-hook.sh
Sourcing setuptools-build-hook
Using setuptoolsBuildPhase
Using setuptoolsShellHook
Sourcing pip-install-hook
Using pipInstallPhase
Sourcing python-imports-check-hook.sh
Using pythonImportsCheckPhase
Sourcing python-namespaces-hook
unpacking sourcesunpacking source archive /nix/store/5q19589r3brxchawyd76xiis1wp9v4d2-source
source root is source
setting SOURCE_DATE_EPOCH to timestamp 315619200 of file source/tox.ini
patching sources
configuring
no configure script, doing nothing
building
Executing setuptoolsBuildPhase
Traceback (most recent call last):
  File "nix_run_setup", line 8, in <module>
    exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\\r\\n', '\\n'), __file__, 'exec'))
  File "/nix/store/5aq2ix4vmk8bxs20ddqi48vc4bnk8zr5-python3-3.8.6/lib/python3.8/tokenize.py", line 392, in open
    buffer = _builtin_open(filename, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'setup.py'
builder for '/nix/store/hvvr2qbhw8c6hyhv52dmmsiam4n87d8w-python3.8-saleor-2.11.1.drv' failed with exit code 1
error: build of '/nix/store/hvvr2qbhw8c6hyhv52dmmsiam4n87d8w-python3.8-saleor-2.11.1.drv' failed

```

The problem I'm coming across is that the application doesn't have a setup.py, and from the [examples](https://github.com/DavHau/mach-nix/blob/master/examples.md) I can't figure out how to make that work.

Please let me know if you have any ideas. *[Link to saleor github](https://github.com/mirumee/saleor)

**Comment by azazel75** [comment]
@epigramengineer A Django app is nor a python package or a python application. What I do is to use mkPython to build a py interpreter with all the dependencies configured. I then use this to run the `manage.py` utility

**Comment by DavHau** [comment]
Het @epigramengineer, could you get your project set up?
I have seen that there is a requirements.txt in the source of the saleor project.
As mentioned by azazel75, it would probably be best to build a python environment from these requirements via `mach-nix.mkPython[Shell]` and then use the manage.py to manage it.

If you want to deploy the project, take a look at [django-nixos](https://github.com/DavHau/django-nixos).
