### ISSUE TITLE
Cannot run mach-nix with "python38" and "lxml==4.6.2"

### ISSUE THREAD

**Issue by rolfschr** [DavHau/mach-nix#224]
Hi,

I'm not sure this an issue with ``mach-nix`` or on my side. I try to install lxml==4.6.2 but it doesn't work. I generally have not much experience with mach-nix so maybe there is a known work-around.
[mach-nix-shell.nix.txt](https://github.com/DavHau/mach-nix/files/5825139/mach-nix-shell.nix.txt)
[requirements.txt](https://github.com/DavHau/mach-nix/files/5825140/requirements.txt)

```bash
rolfschr@rolf-ThinkPad-T470:~/src/test$ cat mach-nix-shell.nix
let
  mach-nix = import (builtins.fetchGit {
    url = "https://github.com/DavHau/mach-nix/";
    ref = "refs/tags/3.1.1";
  }) { python = "python38"; };
in mach-nix.mkPythonShell {
  requirements = builtins.readFile ./requirements.txt;
}

rolfschr@rolf-ThinkPad-T470:~/src/test$ cat requirements.txt
lxml==4.6.2

rolfschr@rolf-ThinkPad-T470:~/src/test$ nix-shell mach-nix-shell.nix
warning: unknown setting 'experimental-features'
building '/nix/store/pdjzmzz11rmi1rqzckxfv024i8g6k8pb-mach_nix_file.drv'...


Some requirements could not be resolved.
Some requirements could not be resolved.
Top level requirements:
Top level requirements:
  lxml==4.6.2
  lxml==4.6.2
Providers:
Providers:
  {'_default': 'wheel,sdist,nixpkgs',
  {'_default': 'wheel,sdist,nixpkgs',
   'gdal': 'nixpkgs',
   'gdal': 'nixpkgs',
   'pip': 'nixpkgs,sdist',
   'pip': 'nixpkgs,sdist',
   'setupmeta': 'wheel',
   'setupmeta': 'wheel',
   'setuptools': 'nixpkgs',
   'setuptools': 'nixpkgs',
   'wheel': 'nixpkgs,sdist'}
   'wheel': 'nixpkgs,sdist'}
Mach-nix version: 3.1.1
Mach-nix version: 3.1.1
Python: 3.8.6
Python: 3.8.6
Cause: Requirements conflict: Requirement.parse('lxml==4.6.2')
Cause: Requirements conflict: Requirement.parse('lxml==4.6.2')
The requirements which caused the error:
The requirements which caused the error:
  lxml==4.6.2
  lxml==4.6.2


builder for '/nix/store/pdjzmzz11rmi1rqzckxfv024i8g6k8pb-mach_nix_file.drv' failed with exit code 1
error: --- Error ------------------------------------------------------------------------------ nix-shell
build of '/nix/store/pdjzmzz11rmi1rqzckxfv024i8g6k8pb-mach_nix_file.drv' failed
(use '--show-trace' to show detailed location information)
```
It works fine with "lxml==4.3.3" (which I did not search specifically for but found out after upgrading from that version to 4.6.2).

**Comment by rolfschr** [comment]
I realize the following is better for reproducibility. I also tried changing the providers.

See [mach-nix-shell.nix.txt](https://github.com/DavHau/mach-nix/files/5825616/mach-nix-shell.nix.txt):

```nix
let
  mach-nix = import (builtins.fetchGit {
    url = "https://github.com/DavHau/mach-nix/";
    ref = "refs/tags/3.1.1";
  }) { python = "python38"; };
in mach-nix.mkPythonShell { # replace with mkPythonShell if shell is wanted
  requirements = "lxml==4.6.2";
  #requirements = "lxml==4.3.3";
  providers = {
    # lxml = "";
  };
}
```

**Comment by DavHau** [comment]
By default, mach-nix accesses a snapshot of the pypi database from the same date as the mach-nix release you are using.
lxml 4.6.2 is probably not yet in that snapshot . (It has been released the same day as the newest mach-nix version).

you can always update the pypi snapshot to a newer version by specifying `pypiDataRev` and `pypiDataSha256` when importing mach-nix.
See mach-nix import example: https://github.com/DavHau/mach-nix/blob/master/examples.md#import-mach-nix

**Comment by rolfschr** [comment]
Perfect, thanks a lot!

``mach-nix`` is a ridiculously helpful tool, thanks so much!
