### ISSUE TITLE
current pypi_db metadata - easy update - error

### ISSUE THREAD

**Issue by InLaw** [DavHau/mach-nix#227]
is there an fast and easy way to get the current pypi_db metadata (if I'm not on master)?
- without to manually copy and past 
```
https://github.com/DavHau/pypi-deps-db/blob/master/PYPI_FETCHER_COMMIT
309e5027910e77bbbb6d2c2e7ccc68432303578a
```
results in :
`unable to download 'https://github.com/DavHau/pypi-deps-db/tarball/309e5027910e77bbbb6d2c2e7ccc68432303578a': HTTP error 404`

---

```
  mach-nix = import (builtins.fetchGit {
    url = "https://github.com/DavHau/mach-nix/" ;
    ref = "refs/tags/3.1.1" ; 
    rev = "1ec92303acd142aa1a3b60bb97745544cf049312" ;
  }) {  
      pkgs = import <nixpkgs>  {config= { allowUnfree = true; };  } ;
      python = "python38" ;  
      pypiDataRev    = "309e5027910e77bbbb6d2c2e7ccc68432303578a";
      pypiDataSha256 = "1dfsmwlqfiahc1amq8pxq1wvj2dd905v9rp1jp8wfjpjgchkj0in";

  } 
```

**Comment by DavHau** [comment]
I guess you confused the projects nix-pypi-fetcher and pypi-deps-db. What you need here is pypi-deps-db.

**Comment by InLaw** [comment]
for me a hint (in the examples) like 
`nix-shell -p nix-prefetch-git --run  "nix-prefetch-git --url https://github.com/davhau/pypi-deps-db --rev refs/heads/master  --no-deepClone" | python -m json.tool - PYPI_DEPS_DB.json` 
would make it more clear

---- 

ideal would be a file where all the commits and hashes would be listed (e.g. via github action which adds each update to the json/list)

**Comment by InLaw** [comment]
https://github.com/DavHau/mach-nix/issues/246
