### ISSUE TITLE
Collision between jupyter and jupyter-core

### ISSUE THREAD

**Issue by TiagoDillenburg** [DavHau/mach-nix#229]
I've installed `ipywidgets` with mach-nix for a project and now I'm unable to install `jupyter` in another project. `nix-shell ./env` is returning this message:

```
collision between /nix/store/r4d1vmafniir2x4pf4v8nnh5f955rgzz-python3.7-jupyter-core-4.7.0/lib/python3.7/site-packages/jupyter.py and /nix/store/p5aigrih43bj04nqcg6rfhm1v6q237pw-python3.7-jupyter-1.0.0/lib/python3.7/site-packages/jupyter.py
```

**Comment by DavHau** [comment]
Thanks for reporting this. I think the `jupyter` package is deprecated/unmaintained. According to https://jupyter.org/install, the correct package to install is `jupyterlab`.

If you actually want to use the old jupyter package you probably have to pin an older version for jupyter-core which doesn't have the colliding jupyter.py file.

Does this solve your problem?

**Comment by TiagoDillenburg** [comment]
Yes, `jupyterlab` package worked. Thanks!
