### ISSUE TITLE
Python version mismatch breaks

### ISSUE THREAD

**Issue by layus** [DavHau/mach-nix#245]
Hi,

I have tried mach-nix and the tool is __awesome__, thanks !

For some reason, my project requires python36, so I edited manually `env/inputs.nix` to change python to `"python36"`. Not sure if this is the right way to go.

Anyway, in `nix-shell env` the environment was wrong because the shell also provides mach-nix, which comes with python3.7. The quick, easy fix for me was to remove mach-nix from the environment. For future users, it is sufficient to delete the following line:

https://github.com/DavHau/mach-nix/blob/8e6913f1a4e797fa0e0c2d966b091023772eae0f/mach_nix/run.py#L94

**Comment by DavHau** [comment]
Thanks for noticing. Changing the python attribute to python36 is fine. But I don't understand why those two python versions mix up for you. 
Could you elaborate a bit more what you mean by `the environment was wrong`. Which package/command did you try? What exactly did not work?

**Comment by DavHau** [comment]
Oh, we should probably build mach-nix via buildPythonApplication instead of buoldPythonPackage here: https://github.com/DavHau/mach-nix/blob/235a0a81d05a043bca2a93442f2560946266fc73/default.nix#L56

**Comment by DavHau** [comment]
fixed via: 51a79318f2f49de0db61d04392b851bdc2cb3121
