### ISSUE TITLE
Helper script to fetch latest pypi-deps-db rev + sha

### ISSUE THREAD

**Issue by rolfschr** [DavHau/mach-nix#246]
Hi,

just wanted to let you know that I have been using the following script auto-generate the ``pypiDataRev`` & ``pypiDataSha256`` attributes. Maybe this is of any help for anyone.

```bash
$ cat get-latest-pypi-deps-db.sh 
#!/usr/bin/env bash

USER_SLASH_REPO="DavHau/pypi-deps-db"

DATA=$(curl "https://api.github.com/repos/$USER_SLASH_REPO/commits/master" | jq '.sha, .commit.author.date' | sed 's/"//g')
COMMIT=$(sed '1q;d' <<< "$DATA")
DATE=$(sed '2q;d' <<< "$DATA")
SHA256=$(nix-prefetch-url --unpack --type sha256 "https://github.com/$USER_SLASH_REPO/tarball/$COMMIT" | tail -n 1)

echo ""
echo "pypiDataRev = \"$COMMIT\"; # $DATE"
echo "pypiDataSha256 = \"$SHA256\";"
```

Thanks for the great work!

**EDIT**: Feel free to close, of course!

**Comment by DavHau** [comment]
Thanks for that. I'm not going to work anymore on improving the current cli. I want to vastly rewrite it completely based on flakes.
Currently it's a pain in the ... that we have so many different `entry points` to mach-nix which all have slightly different ways of managing dependencies.

My plan is to have some kind of `mach-nix init` which initializes a flake into the current directory. And other `mach-nix ...` commands will just be convenience wrappers around `nix flake ...` calls. For compatibility with non-flake compatible nix we can use edolstras flake-compat.nix

**Comment by DavHau** [comment]
I now opened: https://github.com/DavHau/mach-nix/issues/277

Feel free to discuss there about ideas/wishes for the new UI
