### ISSUE TITLE
py pkg cherrypy # collision between `python3.8-jaraco.functools-3.0.1/lib/python3.8/site-packages/jaraco/__pycache__/__init__.cpython-38.pyc' and `python3.8-jaraco.collections-3.0.0/lib/python3.8/site-packages/jaraco/__pycache__/__init__.cpython-38.pyc'

### ISSUE THREAD

**Issue by InLaw** [DavHau/mach-nix#248]
`nix-shell -p nixFlakes --run "nix run github:davhau/mach-nix#with.cherrypy --show-trace "`

error:
```
builder for '/nix/store/9iy8zm3xp9adx2gkgdl6ynjnn6ig3znp-python3-3.8.6-env.drv' failed with exit code 25; last 1 log lines:
  collision between `/nix/store/i4l157wn29rsk5qqsb6qkdyzcfs6lccy-python3.8-jaraco.functools-3.0.1/lib/python3.8/site-packages/jaraco/__pycache__/__init__.cpython-38.pyc' and `/nix/store/hdy6q6qdirhnh6g2yvpr0i61kmkyrz9c-python3.8-jaraco.collections-3.0.0/lib/python3.8/site-packages/jaraco/__pycache__/__init__.cpython-38.pyc'
error: --- Error --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- nix
build of '/nix/store/9iy8zm3xp9adx2gkgdl6ynjnn6ig3znp-python3-3.8.6-env.drv' failed
```

**Comment by DavHau** [comment]
This is an actual collision, meaning that two different python packages have a module with the exact same name. That collision will also happen when using pip. Just pip doesn't catch those things and leaves it up to chance which module will be loaded on `import jaraco`.

This problem should be fixed upstream I guess.

**Comment by InLaw** [comment]
e.g. via pip works 
`pkg="zope"; docker run --rm -it python:3.8  python -c "import pip; package_names=[ '"${pkg}"', ] ; pip.main([ 'install' ] + package_names); import "${pkg}" "`

**Comment by DavHau** [comment]
Yes, it works, as it will also most likely work when you set `ignoreCollisions = true` in nix.
Pip just doesn't care if one package overwrites the file of another. And probably these packages are designed in a way where this somehow works. But is it good package design? I think not.

**Comment by InLaw** [comment]
sorry, it's late (for me)..

Thanks for you fast response.

----

What would be the easiest way to omit the e.g. jaraco.functools package in one of the sub-packages/dependent packages?

An "idea" would be to delete it from the package but add it as requrement
_.cherrypy.buildInputs.mod =     oldInputs: filter (inp:  py."jaraco.functools" ) oldInputs;
-> how to use the filter? (undefined variable 'filter')

----

Sorry if that question has been raised 
- is there a way to configure "ignoreCollisions = true" on package level?

**Comment by DavHau** [comment]
The filter function is a nix builtin and referenced via 'builtins.filter'. See the manual: https://nixos.org/manual/nix/unstable/expressions/builtins.html

I don't know if there is a ignoreCollisions on a package level. I never tried. I prefer to resolve the collision on a package level.

You could for example override the 'postBuild' or  'postInstall' hook for one of the packages and remove the colliding file there

That way, you're the one who decides which file to ignore instead of leaving it up to chance.
