### ISSUE TITLE
flowutils: "there was probably a problem while crawling pypi"

### ISSUE THREAD

**Issue by p4block** [DavHau/mach-nix#252]
Been having this issue for a few months, just doing what I'm told :grin: 

```
The Package 'flowutils' is not available from any of the selected providers {'nixpkgs', 'sdist', 'wheel'}
 for the selected python version
If the package's initial release date predates the release date of mach-nix, either upgrade mach-nix itself or manually specify 'pypi_deps_db_commit' and
'pypi_deps_db_sha256 for a newer commit of https://github.com/DavHau/pypi-deps-db/commits/master
If it still doesn't work, there was probably a problem while crawling pypi.
Please open an issue at: https://github.com/DavHau/mach-nix/issues/new
```

My shell.nix:
```
let pkgs = import <nixpkgs> {};

  mach-nix = import (builtins.fetchGit {
    url = "https://github.com/DavHau/mach-nix/";
    ref = "refs/tags/3.1.1";
  }) {
    python = "python38";
  };

  python-with-requirements = mach-nix.mkPython {
    #requirements = builtins.readFile ./requirements.txt;
    requirements = ''
      pandas
      numpy
      scikit-learn
      umap-learn
      hdbscan
      plotly
      matplotlib
      joblib==0.17.0
      FlowUtils
      FlowKit
    '';

    providers = {
     # _default = "sdist,nixpkgs";
      hdbscan = "nixpkgs";
    };

  };
in pkgs.mkShell {
  buildInputs = with pkgs; [
    python-with-requirements
  ];
}
```

[This is the package in question](https://pypi.org/project/FlowUtils/)

**Comment by InLaw** [comment]
https://github.com/whitews/flowutils
FlowUtils is available via the pip command. 
- However, NumPy must be installed **prior** in order to compile the C extensions.

**Comment by mschwaig** [comment]
I have not run your code, but that error message you posted is outdated. You actually have to set `pypiDataRev` and `pypiDataSha256` on import like this:
```
  mach-nix = import (builtins.fetchGit {
    url = "https://github.com/DavHau/mach-nix/";
    ref = "refs/tags/3.1.1";
  }) {
  python = "python38";
  pypiDataRev = "[newer rev commit hash]";
  pypiDataSha256 = "[nar hash of newer rev]";
};
```
I have opened a PR about the outdated error messagea few days ago: https://github.com/DavHau/mach-nix/pull/268.

**Comment by DavHau** [comment]
The flowutils package requires dependencies before calling setuptools. Therefore the extractor failed.

As a demonstration on how this can be fixed I openend an upstream PR: https://github.com/whitews/FlowUtils/pull/8

But I'm not going to do this again in the future ;)

BTW, since the recent crawler update, you can now see exactly which errors occurred during dependency extraction by checking [pypi-deps-db/sdist-errors](https://github.com/DavHau/pypi-deps-db/tree/master/sdist-errors)

**Comment by DavHau** [comment]
Oh and of course, for any package not available from the DB, you can always manually build it via `mach-nix.buildPythonPackage` and then include it via `packagesExtra`.
