### ISSUE TITLE
Collision when using `swifter`

### ISSUE THREAD

**Issue by Narice** [DavHau/mach-nix#255]
collision between:
`/nix/store/zn4ksalrynlx3iwd4d0ldq7aiqn84ysv-python3.8-opencensus-context-0.1.2/lib/python3.8/site-packages/opencensus/common/__pycache__/__init__.cpython-38.pyc`
and
`/nix/store/2cfyjnic605mjr5j7zck88gk7bkqwpim-python3.8-opencensus-0.7.12/lib/python3.8/site-packages/opencensus/common/__pycache__/__init__.cpython-38.pyc`

the issue can be tested simply with this command line:
`nix shell github:davhau/mach-nix#shellWith.swifter`

or with this `flake.nix` file:
```nix
{
  description = "Using mach-nix from a flake";

  inputs = {
    nixpkgs.url = github:NixOS/nixpkgs/nixos-unstable;
    mach-nix.url = github:DavHau/mach-nix/master; # v3.0.0 release tag
  };

  outputs = { self, nixpkgs, mach-nix }: let
    system = "x86_64-linux";
    pkgs = (import nixpkgs { inherit system; }).pkgs;
    mach-nix-utils = import mach-nix {
      inherit pkgs;
      python = "python3";
    };
    requirements = ''
      #matplotlib
      #pandas
      #numpy
      #scikit-learn
      #ipykernel
      #nbconvert
      #notebook
      #seaborn
      #graphviz
      swifter
    '';
  in {
    devShell."${system}" = mach-nix-utils.mkPythonShell {
        inherit requirements;
    };
  };
}
```

**Comment by Narice** [comment]
I saw #185 and #201 so I thaught it was a good idea to report this here.
However, do you think it could be an upstream bug?

**Comment by DavHau** [comment]
Hey, thanks for reporting this. This is not a mach-nix bug. `opencensus-context` and `opencensus` are two different packages which both provide a file with the exact same import path.
I just added a troubleshooting section to examples.md with some explanation why this happens and how to fix that.
Please have a look at it, and let me know if this helps you.

**Comment by DavHau** [comment]
This here should work:
```nix
let
  mach-nix = import (builtins.fetchGit {
    url = "https://github.com/DavHau/mach-nix/";
    ref = "refs/tags/3.2.0";
  }) {};

in
mach-nix.mkPython {
  requirements = ''
    swifter
  '';
  _.opencensus-context.postInstall = ''
    rm $out/lib/python3.8/site-packages/opencensus/common/__pycache__/__init__.cpython-38.pyc
    rm $out/lib/python3.8/site-packages/opencensus/__pycache__/__init__.cpython-38.pyc
  '';
}

```

**Comment by Narice** [comment]
Oh! I didn't see your message, sorry for the late reply
I succeeded in installing the pqckage in another way but I'm happy it was a useful feedback
