### ISSUE TITLE
How to install pre-release packages from Pypi?

### ISSUE THREAD

**Issue by radoye** [DavHau/mach-nix#263]
What is the way to install a package like [selenium 4.0.0-beta-3](https://pypi.org/project/selenium/4.0.0.b3/#files)? Doing the standard thing 

```nix
let
  mach-nix = import (builtins.fetchGit {
    url = "https://github.com/DavHau/mach-nix/";
    ref = "refs/tags/3.2.0";
  }) {};
in
mach-nix.buildPythonPackage {
  src = mach-nix.fetchPypiWheel "selenium" "4.0.0.b3" "selenium-4.0.0.b3-py3-none-any.whl"; # not sure about this "filename"
}
```
fails with

```bash
error: attribute '4.0.0.b3' missing, at /nix/store/6ag13iwd3mvyyplma4vbzm19dyrz64il-nix-pypi-fetcher-src/default.nix:23:17
```

However, `pip install --pre selenium==4.0.0.b3` works just fine.

**Comment by DavHau** [comment]
Hey, for very recent packages it might be best to specify the direct URL to the package's wheel file. You can get the download URL from pypi.org after searching for the package there

Just pass the URL as a string via `src`.

Please let me know if that worked for you.

**Comment by DavHau** [comment]
Actually I forgot that on-the-fly requirements extraction is not yet supported for .whl files, therefore you will have to specify them manually via `requirements` and also set `format="wheel"`.

Alternatively you could just update your pypiData and reference a newer revision of https://github.com/DavHau/pypi-deps-db
Check the examples on how to [import mach-nix with a newer pypiData](https://github.com/DavHau/mach-nix/blob/master/examples.md#import-mach-nix)

**Comment by DavHau** [comment]
closing and tracking feature request via: https://github.com/DavHau/mach-nix/issues/276
