### ISSUE TITLE
Requirements conflict

### ISSUE THREAD

**Issue by domenkozar** [DavHau/mach-nix#274]
[here](https://github.com/nix-dot-dev/nix.dev/pull/145) I'm trying to use mach-nix to replace pypi2nix.

Given `shell.nix`:

```nix
let
  mach-nix = import (builtins.fetchGit {
    url = "https://github.com/DavHau/mach-nix/";
    ref = "refs/tags/3.2.0";
  }) {};
in
mach-nix.mkPythonShell {
  requirements = builtins.readFile ./requirements.txt;
}
```

and 

```
$ cat requirements.txt 
sphinx==4.0.1
alabaster==0.7.12
livereload==2.6.3
sphinx-copybutton==0.3.1
```

I get the error:

```
building '/nix/store/psmissyqjdjic98sl0nk04pspmiajgh6-mach_nix_file.drv'...

Some requirements could not be resolved.
Top level requirements:
  sphinx==4.0.1  alabaster==0.7.12  livereload==2.6.3  sphinx-copy-utton==0.3.1
Providers:
  {'_default': 'wheel,sdist,nixpkgs',
   'gdal': 'nixpkgs',
   'pip': 'nixpkgs,sdist',
   'setupmeta': 'wheel',
   'setuptools': 'nixpkgs',
   'wheel': 'nixpkgs,sdist'}
Mach-nix version: 3.2.0
Python: 3.8.8
Cause: Requirements conflict: Requirement.parse('sphinx==4.0.1')
The requirements which caused the error:
  sphinx==4.0.1

builder for '/nix/store/psmissyqjdjic98sl0nk04pspmiajgh6-mach_nix_file.drv' failed with exit code 1
error: build of '/nix/store/psmissyqjdjic98sl0nk04pspmiajgh6-mach_nix_file.drv' failed
(use '--show-trace' to show detailed location information)
```

It's not clear to me why that's failing as requirement.txt otherwise works.

**Comment by DavHau** [comment]
That's just because you're referencing a very recent version of sphinx which is not part of the dependency DB snapshot used by this mach-nix version.

Just update the deps db during mach-nix import to a more recent version like this for example:
```nix
let
  mach-nix = import (builtins.fetchGit {
    url = "https://github.com/DavHau/mach-nix/";
    ref = "refs/tags/3.2.0";
  }) {
    pypiDataRev = "15175225c8295e08e5b95b2965892820a64e9746";
    pypiDataSha256 = "00f87qsdg312iy5f47vr3jjw1jd3d0j89n6zmja536im5f1qzrs9";
  };
in
```

I know the reporting of the resolver is not very helpful. I'll hope to switch to libsolv at some point in the future which should produce more helpful errors.

**Comment by domenkozar** [comment]
Thanks for the quick response!

Until libsolv is used, I'd suggest changing README to always specify `pypiData*` so that it's explicit to the user what revision of pypi is used. Also a short documentation section how to get the latest `rev` and its hash would help.

**Comment by DavHau** [comment]
I now included a hint in the error message about the possibility of an outdated DB and a recommendation on how to fix it.
