### ISSUE TITLE
How to build when pytest tests break ?

### ISSUE THREAD

**Issue by 573** [DavHau/mach-nix#28]
I am trying to build my config ([here](http://ix.io/2pAs), see #24) with python via mach-nix, but on a different architecture (aarch64) and now get [this errors](http://ix.io/2pA9).

Adding
```
requirements = ''
        pytest
        ...
'';
pytest = pkgs.python3Packages.pytest.overridePythonAttrs {
      doCheck = false;
      doInstallCheck = false;
    };
```

does not seem to solve it.

**Comment by DavHau** [comment]
First of all, I think your `pytest =` statement does not have any effect. The pytest variable is not used. 
The second thing i just noticed right now is, that `do(install)Check = false;` doesn't have any effect when using `overridePythonAttrs`. It works when using `overrideAttrs`. Maybe this needs to be changed in mach-nix. It also uses `overridePythonAttrs` internally which might be wrong.

My recommended way of overriding python packages is:
(sorry there is no proper documentation about it to this date)
```nix
let
  mach-nix = import (builtins.fetchGit {
    url = "https://github.com/DavHau/mach-nix/";
    ref = "2.0.0";
  });
in mach-nix.mkPython {

  requirements = ''
    pytest
  '';
  providers = {
    pytest = "nixpkgs";
  };
  overrides_pre = [( pythonSelf: pythonSuper: {
    pytest = pythonSuper.pytest.overrideAttrs ( oldAttrs: {
      doCkeck = false;
      doInstallCheck = false;
    });
  })];
}
```

**Comment by DavHau** [comment]
Version 2.0.1 has a bunch of fixes which should make `disable_checks` work like expected. Therefore the discussed overrides should not be necessary anymore.

Please reopen anytime in case it still doesn't work.

**Comment by 573** [comment]
I am using v2.1.1 now.
For the `html5lib` python package requirement I still needed to add the `overrides_pre` pattern to suppress the otherwise failing tests but for the rest which is a lot `disable_checks` just works.
