### ISSUE TITLE
Distlib not comparing version '3.10' correctly

### ISSUE THREAD

**Issue by francescocarzaniga** [DavHau/mach-nix#287]
Consider the following derivation:
```
{ pkgs ? import <nixpkgs> {} }:                                                         /* import all standard nix packages */

let
  mach-nix = import (
    builtins.fetchGit {
      url = "https://github.com/DavHau/mach-nix/";
      ref = "3.2.0";
    }) {

      pypiDataRev = "e723ab9fa1527957ee6d9f498ddb6fbf52f739a7";
      pypiDataSha256 = "1wxqbj8h3cgdhq69xxl7c2z7lxn8snvb5lqq5qk40bgsxp5168hp";

      python = "python38";                                                                      /* define python version */
    };

  pythonPackages = mach-nix.mkPython {                                          /* import all necessary python packages */
    requirements = ''
      cobra
      biopython
    '';
    providers = {
      "ruamel.yaml" = "nixpkgs";                                                        /* need to build this specific package from source due to cobra */
    };
  };

  RPackages = with pkgs; [                                                                      /* import all necessary R packages */
  ];

  linuxPackages = with pkgs; [                                                          /* import all necessary standard linux packages */
  ];

in

pkgs.mkShell {
  buildInputs = [ pythonPackages ] ++ RPackages ++ linuxPackages;
}
```
It works fine, except for the fact that I have to specify `ruamel.yaml` manually. If however I switch to `3.3.0`, it breaks with
```
ERROR: Could not find a version that satisfies the requirement ruamel.yaml.clib>=0.1.2; platform_python_implementation == "CPython" and python_version < "3.10" (from ruamel-yaml)
ERROR: No matching distribution found for ruamel.yaml.clib>=0.1.2; platform_python_implementation == "CPython" and python_version < "3.10"
```
and the provider trick does not work.

**Comment by DavHau** [comment]
Thanks, this seems to be due to a bug in distlib. I just opened an issue there: https://bitbucket.org/pypa/distlib/issues/149/mistake-in-comparing-python-versions

**Comment by DavHau** [comment]
@francescocarzaniga , until this is fixed, you can fix it by manually injecting the missing dependency like this for example:
```
mach-nix.mkPython {
    requirements = ''
      ruamel.yaml
      ruamel.yaml.clib
    '';
    _."ruamel.yaml".propagatedBuildInputs.mod = pySelf: oldAttrs: oldVal: oldVal ++ [ pySelf."ruamel.yaml.clib" ];
  };

```

**Comment by francescocarzaniga** [comment]
@DavHau Great! I can confirm that this trick, on ruamel.yaml.clib (dependency of ruamel.yaml) and zipp (dependency of importlib-resources), solves the issue at least temporarily.

**Comment by InLaw** [comment]
almost (for my case)

```
 #ruamel.yaml
  ruamel.yaml.clib
```
else it will result in:
```

/build/dist /build
Processing ./ruamel.yaml-0.17.4-py3-none-any.whl
ERROR: Could not find a version that satisfies the requirement ruamel.yaml.clib>=0.1.2; platform_python_implementation == "CPython" and python_version < "3.10" (from ruamel.yaml==0.17.4) (from versions: none)
ERROR: No matching distribution found for ruamel.yaml.clib>=0.1.2; platform_python_implementation == "CPython" and python_version < "3.10" (from ruamel.yaml==0.17.4)
builder for '/nix/store/pxlmnfh11gykslvh6wwjfa4lshzl127h-python3.8-ruamel.yaml-0.17.4.drv' failed with exit code 1
cannot build derivation '/nix/store/mqchh1ik4k060bv7l0ynaaxmhzb7z3ri-python3-3.8.5-env.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/d4khp5h2xw88qgwbl4lrxhj45jgw87rv-bEnvJL.drv': 1 dependencies couldn't be built
error: build of '/nix/store/d4khp5h2xw88qgwbl4lrxhj45jgw87rv-bEnvJL.drv' failed
```
----

thanks for opening the issue but not sure if there will be a fast response ..
"This repository's ownership is pending transfer to PyPA. Visit the repository details page for more info. "


----

I think I will stay with 

`ruamel.yaml<=0.16.12`

**Comment by DavHau** [comment]
@InLaw You need to inject the missing dependency manually like in the above example. This line will fix it:
```
_."ruamel.yaml".propagatedBuildInputs.mod = pySelf: oldAttrs: oldVal: oldVal ++ [ pySelf."ruamel.yaml.clib" ];
```

**Comment by DavHau** [comment]
> thanks for opening the issue but not sure if there will be a fast response ..
"This repository's ownership is pending transfer to PyPA. Visit the repository details page for more info. "

I might just switch to setuptools for evaluating markers. It should be well maintained.

**Comment by francescocarzaniga** [comment]
> I might just switch to setuptools for evaluating markers. It should be well maintained.

That's what I wanted to suggest (but I didn't know how much time you wanted to invest on this issue), as distlib just does a simple arithmetic operation and it would take significant refactoring to handle version numbers well.

**Comment by PierreR** [comment]
We hit the same issue today as well ;-)

**Comment by DavHau** [comment]
`distlib` is dead and I think we should replace its use by `packaging`. Currently we are using `distlib` only for interpreting requirement markers.
`packaging` has that capability as well according to their readme: https://pypi.org/project/packaging/#description

**Comment by DavHau** [comment]
Oh actually, there seems to be a fix: https://bitbucket.org/pypa/distlib/commits/b39a35ad43005d127de2b7b949d3ffa60e046733
So we could just update the dependency.

**Comment by TyberiusPrime** [comment]
Appreciate it, this fixes it beautifully.
