### ISSUE TITLE
unsupported argument 'fetchSubmodules' to 'fetchGit'

### ISSUE THREAD

**Issue by adamlwgriffiths** [DavHau/mach-nix#297]
I'm specifying a `fetchGit` repository and including `fetchSubmodules`
```
let
  mach-nix = import (builtins.fetchGit {
    url = "https://github.com/DavHau/mach-nix/";
    ref = "3.3.0";
  }) {};
  raylib-python-cffi = mach-nix.buildPythonPackage {
    src = builtins.fetchGit {
      url = "https://github.com/electronstudio/raylib-python-cffi/";
      ref = "master";
      rev = "a15d6e2d2ec8ce39e90c101164d460b9797e0c11";
      fetchSubmodules = true;
    };
  };
... <snip>
```

I get the following error:

`unsupported argument 'fetchSubmodules' to 'fetchGit', at /home/adam/Workspace/koine-py/shell.nix:28:7`

I'm not sure what's causing this, because I believe this is using the Nixpkgs builtin and not Mach-nix, and it should support "fetchSubmodules".
I'm running Nix 20.09, from what I can tell that should [support fetchSubmodules](https://github.com/NixOS/nixpkgs/blob/nixos-20.09/pkgs/build-support/fetchgit/default.nix#L16) without any trouble.

Any help understanding what's going on would be appreciated.

**Comment by bjornfor** [comment]
nixUnstable accepts a 'submodules = true' argument. But not nixStable (2.3.x).

**Comment by bjornfor** [comment]
The doc you're referring to is for nixpkgs (pigs.fetchgit), but the function you call is a Nix builtin.

**Comment by adamlwgriffiths** [comment]
Ah ok, thanks for clarifying.
So what do I do to utilise nixUnstable builtin's in a nix shell?

**Comment by bjornfor** [comment]
>So what do I do to utilise nixUnstable builtin's in a nix shell?

You have to install nixUnstable. (The builtins are tied to the Nix distribution -- they're built-in :-) )

**Comment by adamlwgriffiths** [comment]
Ok thanks for clarifying.
