### ISSUE TITLE
Private conda channels?

### ISSUE THREAD

**Issue by mausch** [DavHau/mach-nix#302]
Hi and thanks for this project!

I'm new to mach-nix, trying to evaluate how suitable it would be for our team.
One thing I don't see mentioned in the docs or code here is private conda channels. If I wanted mach-nix to work with a private conda channel I guess I'd have to build and maintain an index like the ones you have at https://github.com/DavHau/conda-channels ?
I see a `condaChannelsExtra` parameter in some nix files, I'm guessing I'd have to pass such a JSON index repo into that parameter?

Many thanks

**Comment by DavHau** [comment]
To use a private channel you just need to download the repodata.json file(s) for your channel and include those via `condaChannelsExtra`. Sorry, there is no docs yet on this. See some examples [here](https://discourse.nixos.org/t/mach-nix-create-python-environments-quick-and-easy/6858/86?u=davhau).

**Comment by mausch** [comment]
Great, thanks! :+1:
