### ISSUE TITLE
flake.lock - No such file or directory

### ISSUE THREAD

**Issue by fiksn** [DavHau/mach-nix#307]
I've installed version 3.3.0 (through `nix-env -if https://github.com/DavHau/mach-nix/tarball/3.3.0 -A mach-nix`) and

` mach-nix gen -r requirements.txt`

yields

`path is '/nix/store/zm6li32ifp9by7k26ii8p340b39wmdjy-9971c5d1a40d4e9ff8159ec6595cb9e91da7d438'
error: opening file '/nix/store/0k1r7yb7pc96hq8qv65vy10pmdb13fpi-mach-nix-3.3.0/lib/python3.8/site-packages/flake.lock': No such file or directory
(use '--show-trace' to show detailed location information)`

**Comment by FlorianFranzen** [comment]
Same here, also happens with  `nix run github:DavHau/mach-nix -- gen -r requirements.txt`:
```
path is '/nix/store/d0c64m91jg6008yx1cglyvm1mb7z8f1b-1ca6b0a0cc38dbba0441202535c92841dd39d1ae'
error: opening file '/nix/store/nh6965qy7w4yr8n0r982cb7vfq45ywjd-mach-nix-master/lib/python3.8/site-packages/flake.lock': No such file or directory
```
Using stable (v3.3.0) results in the same issue `nix run github:DavHau/mach-nix/3.3.0 -- gen -r requirements.txt`
```
path is '/nix/store/zm6li32ifp9by7k26ii8p340b39wmdjy-9971c5d1a40d4e9ff8159ec6595cb9e91da7d438'
error: opening file '/nix/store/0k1r7yb7pc96hq8qv65vy10pmdb13fpi-mach-nix-3.3.0/lib/python3.8/site-packages/flake.lock': No such file or directory
