### ISSUE TITLE
Why do I get this error

### ISSUE THREAD

**Issue by jakobneufeld** [DavHau/mach-nix#361]
path is '/nix/store/zm6li32ifp9by7k26ii8p340b39wmdjy-9971c5d1a40d4e9ff8159ec6595cb9e91da7d438'
error: opening file '/nix/store/0k1r7yb7pc96hq8qv65vy10pmdb13fpi-mach-nix-3.3.0/lib/python3.8/site-packages/flake.lock': No such file or directory

**Comment by DavHau** [comment]
This is due to a bug which should be fixed on the master branch. Could you try again on master and confirm?

**Comment by jakobneufeld** [comment]
I fixed it @DavHau. Question do you know how to fix the error I mentioned in the nixpkgs repo?

**Comment by jakobneufeld** [comment]
I fixed alot of bugs. However I know get this bug @DavHau 
    last 10 log lines:
       > Mach-nix version: 3.3.0
       > Python: 3.8.9
       > Cause: Requirements conflict: Requirement.parse('amulet-core>=1.4.8')
       > The requirements which caused the error:
       >   amulet-core>=1.4.8
       >
       > The given requirements might contain package versions which are not yet part of the dependency DB
       > currently used. The DB can be updated by specifying 'pypiDataRev' when importing mach-nix.
       > For examples see: https://github.com/DavHau/mach-nix/blob/master/examples.md
       >

**Comment by jakobneufeld** [comment]
How can I fix this?
@DavHau

**Comment by NikolayTach** [comment]
Отправлено с iPhone
