### ISSUE TITLE
Default python is `python3` but `python38` hardcoded at some places

### ISSUE THREAD

**Issue by vincentbernat** [DavHau/mach-nix#372]
Hey!

I have noticed that when not specifying a Python interpreter, we get `python3`, which actually is `python39`, but there are some places where `python38` is hard-coded. From a cold store, we download both `python38` and `python39` and also, there are some builds done for Python 3.8 that could be avoided.

Any reason we don't replace `python38` by `python3`?

**Comment by DavHau** [comment]
The python version of the mach-nix tool itself should be pinned, as we do not test it against all python versions. Therefore currently the tool will always use 3.8 even if you build a 3.9 environment

**Comment by vincentbernat** [comment]
Thanks! Understood.
