### ISSUE TITLE
add nix version check

### ISSUE THREAD

**Issue by exarkun** [DavHau/mach-nix#385]
I'm not exactly sure how this one is getting triggered.  It happens on CI runs for a branch I'm working on.  It doesn't happen for me locally.  I guess it might have something to do with how CircleCI does the git clone (it does weird stuff instead of a normal `git clone ...`).

```
unpacking 'https://github.com/davhau/mach-nix/archive/bdc97ba6b2ecd045a467b008cff4ae337b6a7a6b.tar.gz'...
unpacking 'https://github.com/NixOS/nixpkgs/archive/0fd9ee1aa36ce865ad273f4f07fdc093adeb5c00.tar.gz'...
error: undefined variable 'isPath' at /nix/store/7jc7pypxw35542y5ib7s9nbsd5j1f5l0-mach-nix-src/default.nix:57:32
```

It is not obvious to me where `isPath` comes from.  I suppose it could be `builtin` or `pkgs.lib` (considering with `with` expressions higher up in that source file.  I didn't manage to find it in either place though.

**Comment by exarkun** [comment]
Hm.  Or I should have looked at `builtins` harder because it is in there.  So why does nix think it is undefined? :/

**Comment by exarkun** [comment]
Ouch.  Because the Docker image CI is using has Nix 2.2.1.  isPath was introduced in 2.3.

I guess there's probably nothing to fix here.  Or maybe mach-nix could declare which version of Nix it requires?  (Saying 2.2.1 is unsupported is probably unnecessary ... but what is the minimum version?)

**Comment by DavHau** [comment]
we could implement a check like:
`builtins.compareVersions builtins.nixVersion "2.3" >= 0`

**Comment by exarkun** [comment]
That seems like a good idea to me.  Maybe it won't make any difference to anyone as long as it is "2.3" but I suppose someday it might change and then maybe it will save someone a little time.
