### ISSUE TITLE
mach-nix flake is not working on my end, an infinite recursion error is being thrown:

### ISSUE THREAD

**Issue by zeta-00** [DavHau/mach-nix#388]
Greetings,

I'm currently using  mach-nix in a shell.nix setup, which is working great, because I can now use nix to run Python packages that I didn't have access to before. But, for some reason the mach-nix( https://github.com/DavHau/mach-nix/blob/master/examples.md#use-mach-nix-from-a-flake ) in the examples section is not working on my end, I'm getting an infinite recursion error thrown?
So, I'm just checking to see if anyone else is getting this error, if not, then that means that there's something wrong with my config.

I'm using (direnv+nix-direnv+emacs-direnv), so getting a mach-nix flake working with this setup would be really nice.

> nix-shell -p nix-info --run "nix-info -m"
 - system: `"aarch64-darwin"`
 - host os: `Darwin 21.2.0, macOS 12.1`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.4`
 - channels(apple): `""`
 - channels(root): `"darwin, home-manager, nixpkgs-unstable-21.11pre311289.503209808cd, nixpkgs-21.11pre309670.253aecf69ed"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`

> nix develop                                                                
error: infinite recursion encountered

       at /nix/store/vbsi61gndh5p7kc3ngwh672kl0zpv6wh-source/flake.nix:17:20:

           16|         pkgs = nixpkgs.legacyPackages."${system}";
           17|         mach-nix = mach-nix.lib."${system}";
             |                    ^
           18|       in {
(use '--show-trace' to show detailed location information)

Thanks in advance for the help.

**Comment by TyberiusPrime** [comment]
Try binding it to a different name, not 'mach-nix' again, so e.g. machNIx = mach-nix.lib...

**Comment by zeta-00** [comment]
Thanks,
Doing that got me past the infinite recursion error, but, now I ran into this error message:
`
> nix develop                                                                                                           
error: The pypiDataRev seems to be older than the nixpkgs which is currently used.
       Because of this, mach-nix might lack dependency information for some python packages in nixpkgs.
       This can degrade the quality of the generated environment or result in failing builds.
       It is recommended to pass a newer pypiDataRev to mach-nix during import.
       For flakes users: Update the `pypi-deps-db` input of mach-nix.
       You can ignore this error by passing 'ignoreDataOutdated = true' to mk* or build* functions
(use '--show-trace' to show detailed location information)
`

Do I need to clone this repo, and running those nix commands in the README.md section?

https://github.com/DavHau/pypi-deps-db

**Comment by Nebucatnetzer** [comment]
I removed the `flake.lock` and that solved it for me after I renamed `mach-nix.lib` to `machNix.lib`.

**Comment by zeta-00** [comment]
I keep getting errors on my end, could you pastebin your mach-nix flake that works for you, thanks.

**Comment by zeta-00** [comment]
I either get the infinite recursion error, or the pypi database outdated error, like I pasted above.

**Comment by Nebucatnetzer** [comment]
No problem I had to fix another problem #389 but this is the working version.
https://github.com/Nebucatnetzer/network_inventory/blob/dev/flake.nix

**Comment by zeta-00** [comment]
@Nebucatnetzer
Thanks, your mach-nix flake works on my end. Maybe we should ask the devs of this mach-nix repo if they could change the flake example in the examples section, so that others don't run into the same issues that we ran into.

**Comment by Nebucatnetzer** [comment]
I'm glad it worked  you :)
Might be an idea but I'm not experienced enough to tell if it's just a problem with the packages I'm trying to use or the example is really outdated.
