### ISSUE TITLE
How to execute a nix expression?

### ISSUE THREAD

**Issue by hykilpikonna** [DavHau/mach-nix#438]
I'm trying to publish a pypi command-line script as a nixos package. Is there a tutorial?

I've wrote my nix script (screenshot below), how do I execute it? I tried `nix-build` and `nix run`, both of them gave errors. 

![image](https://user-images.githubusercontent.com/22280294/165140270-c8bd6f13-8666-4365-a472-dd3904ecb711.png)
![image](https://user-images.githubusercontent.com/22280294/165140298-14e9d9ca-1605-4622-9e70-009ed3fe7e43.png)

**Comment by DavHau** [comment]
Remove line 17 and 18.
Also the URL should be a tarball url, like for example: `https://github.com/hykilpikonna/hyfetch/tarball/master`

**Comment by hykilpikonna** [comment]
> Remove line 17 and 18. Also the URL should be a tarball url, like for example: `https://github.com/hykilpikonna/hyfetch/tarball/master`

Thank you!
