### ISSUE TITLE
Installing a package built using nixpkgs' default buildPythonPackage (in a flake)

### ISSUE THREAD

**Issue by charlesbaynham** [DavHau/mach-nix#453]
Firstly, thanks for an awesome package. 

Secondly, is there a way to include "normal" python packages built using buildPythonPackage into an environment, but which are not present in nixpkgs?

Specifically, I'm trying to define a python environment in a flake which includes a package (called artiq) which is another flake, and which outputs itself as a buildPythonPackage package (https://github.com/m-labs/artiq). I'm trying to mix this with other packages that have been built using mach-nix.

It sounds like mach-nix is able to parse packages out of nixpkgs if they're listed in a requirements file, so I tried to pass something like:

```
devShell = pkgs.mkShell {
        name = "artiq-environment";
        buildInputs = [
          (
            mach-nix.lib.x86_64-linux.mkPython {
            requirements = builtins.readFile ./requirements.in + ''
              artiq
            '';
            packagesExtra = MachNixPackages;
          })
        ]
      };
```

having already make an overlay for pkgs like so:

```
artiq_overlay = self: super:
        {
          python = super.python.override {
            packageOverrides = self: super: {
              artiq = artiq.packages.x86_64-linux.artiq;
            };
          };
          pythonPackages = self.python.pkgs;

          artiq = artiq.packages.x86_64-linux.artiq;
        };

pkgs = import nixpkgs { system = "x86_64-linux"; overlays = [ artiq_overlay ]; };
```

This didn't work however, because the nixpkgs used by mach-nix isn't overlayed, so it can't see `artiq`. 

Is this possible somehow?

Thanks!

**Comment by bjornfor** [comment]
I'm not sure how mach-nix is set up in (that) flake, but I think you must pass your final nixpkgs set (`pkgs`) to mach-nix, or else it won't know about the extra package.

When not using flakes, that's done like this: https://github.com/DavHau/mach-nix/blob/master/examples.md#import-mach-nix

Alternatively, if you directly pass your custom package to `packagesExtra`, I think that should work?

**Comment by charlesbaynham** [comment]
@bjornfor that makes sense, though I wasn't sure how to do it. I'll give it a try using the `pkgs ` attribute for importing `mach-nix`, which might help a lot.

**Comment by charlesbaynham** [comment]
OK I have now given this a try. I imported mach-nix in a flake like so:

```
artiq_overlay = self: super:
    {
        python = super.python.override {
        packageOverrides = self: super: {
            artiq = artiq.packages.x86_64-linux.artiq;
        };
        };
        pythonPackages = self.python.pkgs;

        artiq = artiq.packages.x86_64-linux.artiq;
    };

pkgs = import nixpkgs { system = "x86_64-linux"; overlays = [ artiq_overlay ]; };

mach-nix-lib = (import mach-nix {
    inherit pkgs;
    dataOutdated = false;
    pypiData = pypi-deps-db;
});
```

And then tried to generate an environment like so:

```
devShells.x86_64-linux.artiq = pkgs.mkShell {
    name = "icl-artiq-environment";
    buildInputs = [
      (mach-nix-lib.mkPython {
        requirements = builtins.readFile ./requirements.in + ''
          artiq
        '';
        packagesExtra = machnixPackages;
      })
    ] ++ nonPythonDeps;
  };
```

Unfortunately, this failed too, with this error:

```
error: builder for '/nix/store/dqk6x1dkckh0x9gmi1nmikisqmnkmvb3-mach_nix_file.drv' failed with exit code 1;
       last 9 log lines:
       >
       > The Package 'artiq' (build: ()) is not available from any of the selected providers ['nixpkgs', 'sdist', 'wheel']
       >  for the selected python version
       > The required package might just not (yet) be part of the dependency DB currently used.
       > The DB can be updated by specifying 'pypiDataRev' when importing mach-nix.
       > For examples see: https://github.com/DavHau/mach-nix/blob/master/examples.md
       > If it still doesn't work, there might have been an error while building the DB.
       > Please open an issue at: https://github.com/DavHau/mach-nix/issues/new
       >
       For full logs, run 'nix log /nix/store/dqk6x1dkckh0x9gmi1nmikisqmnkmvb3-mach_nix_file.drv'.
```

So it sounds like mach-nix isn't able to find artiq in the pypi-deps-db (because it isn't there) and therefore doesn't know how to solve it as a dependancy. Makes sense. 

So I'm now stuck: presumable mach-nix has a way of dealing with nixpkgs packages since it is capable of using these. Is there a way I can invoke this manually somehow, to convert them into a mach-nix package instead? Or is there a better way of passing a non-mach-nix package in?

**Comment by charlesbaynham** [comment]
This comment in the readme seems intruiging:

```
overridesPre (list): (advanced) list of pythonOverrides to apply before the mach-nix overrides. Use this to include additional packages which can then be selected inside the requirements
```

Is there a way I can use this to do what I'm trying to do?

**Comment by charlesbaynham** [comment]
Alright, a slightly simpler approach but that still doesn't quite work. I think I'm getting closer though. Here's a MWE:

```
{
  inputs = {
    nixpkgs.follows = "artiq/nixpkgs";
    artiq.url = "github:m-labs/artiq";
    mach-nix.url = "mach-nix";
  };

  outputs =
    { self, artiq, nixpkgs, mach-nix }:
    let
      pkgs = import nixpkgs { system = "x86_64-linux"; };
      artiq_override = self: super: {
        artiq = artiq.packages.x86_64-linux.artiq;
      };

    in
    rec {
      devShell.x86_64-linux = pkgs.mkShell {
        name = "artiq-environment";
        buildInputs = [
          (mach-nix.lib.x86_64-linux.mkPython {
            requirements = ''
              artiq
            '';
            overridesPre = [ artiq_override ];
            providers = {
              artiq = "nixpkgs";
            };
          })
        ];
      };
    };
}
```

I think this is how `overridesPre` is intended to be used. This results in `artiq` appearing in the `nixpkgs-py-pkgs-json` list. However this still gives the same error:

```
error: builder for '/nix/store/hm3s0nn52w0kbbydpf5lwazs370zbh1c-mach_nix_file.drv' failed with exit code 1;
       last 10 log lines:
       > Mach-nix version: master
       > Python: 3.9.9
       > Cause: Requirements conflict: artiq
       > The requirements which caused the error:
       >   artiq
       >
       > The given requirements might contain package versions which are not yet part of the dependency DB
       > currently used. The DB can be updated by specifying 'pypiDataRev' when importing mach-nix.
       > For examples see: https://github.com/DavHau/mach-nix/blob/master/examples.md
       >
       For full logs, run 'nix log /nix/store/hm3s0nn52w0kbbydpf5lwazs370zbh1c-mach_nix_file.drv'.
(use '--show-trace' to show detailed location information)
```

I've also tried trying to cheat mach-nix into thinking that `artiq` is a mach-nix package by defining the overlay like so:

```
artiq_override = self: super: {
        artiq = artiq.packages.x86_64-linux.artiq // { requirements = ""; };
      };
```

But same problem. I must be missing how to get mach-nix to use the version in nixpkgs without checking pypi-deps-db - it's able to do this for other package built using mach-nix itself, so it must be possible somehow. 

So my goal now is either
a) Get mach-nix to treat artiq as a mach-nix package, even though it's not. This might cause weird problems that I don't understand. 
or
b) Get mach-nix to import artiq into itself as it can do for nixpkgs packages. This is exactly what I want, but I can't seem to stop it looking up pypi-deps-db.

**Comment by charlesbaynham** [comment]
I have now resolved this: it turns out I was chasing a red herring. There were a couple of problems which I encountered along the way because of details of the package I'm installing which I'll follow up in separate issues, but the approach I was using to add a non-mach-nix package to a mach-nix environment was correct. 

For future investigators, this is the way I did it:

```
    devShells.x86_64-linux.default = pkgs.mkShell {
        name = "my-environment";
        buildInputs = [
          (mach-nix.lib.x86_64-linux.mkPython {
            requirements = ''
              numpy  # (for example - I actually need more)
              some-package
            '';
            overridesPre = [ self: super: {
              some-package= some-package.packages.x86_64-linux.some-package;
            } ];
          })
        ];
      };
```
