### ISSUE TITLE
setuptools update /nixpkgs 21.11 breaks setup.cfg:install_requires packages

### ISSUE THREAD

**Issue by TyberiusPrime** [DavHau/mach-nix#473]
Updating to 21.05 to 22.05, I've found my python packages breaking with 
"Automatic requirements extraction failed for [pkg]".

It's affecting all packages that were declaring their requirements 
via 'install_requires' in setup.cfg

Bisecting nixpkgs, the relevant nixpkgs commit is:
5c09870c024 python3Packages.setuptools: 57.2.0 -> 60.8.2

Haven't had a chance to dig into the root cause yet.

Flake showing the issue
```
{
  inputs = {
    # this one breaks: python3Packages.setuptools: 57.2.0 -> 60.8.2
    nixpkgs.url = "github:NixOS/nixpkgs?rev=5c09870c0244bbcf47a84f379e05bf10c7aa3f0d";
    # the one just before that works
    #nixpkgs.url = "github:NixOS/nixpkgs?rev=bcad3669e8b2b32bdaeace0618f02393121a41bf";
    mach-nix = {
      url = "github:DavHau/mach-nix?rev=7e84a4e8fe088449abfa22476ad35c6cf493cad1";
      inputs.nixpkgs.follows = "nixpkgs";
    };
  };

  outputs = flakes @ {
    self,
    nixpkgs,
    mach-nix,
  }: let
    pkgs = import nixpkgs {system = "x86_64-linux";};
    mach-nix_ = (import flakes.mach-nix) {
      inherit pkgs;
    };
    dppd = mach-nix_.buildPythonApplication rec {
      pname = "dppd";
      version = "0.1";
      src = pkgs.fetchFromGitHub {
        owner = "TyberiusPrime";
        repo = "dppd";
        rev = "b55ac32ef322a8edfc7fa1b6e4553f66da26a156";
        sha256 = "sha256-fyDDeJRbm9hMkefqiyxHazZut38rxgZVcyp+YpUglGI=";
      };
    };
  in {
    defaultPackage.x86_64-linux = dppd;
  };
}
```

**Comment by bjornfor** [comment]
Duplicate of https://github.com/DavHau/mach-nix/issues/467.

**Comment by TyberiusPrime** [comment]
Should've searched for the causing commit, instead of trying to look for keywords. Thanks bjornfor!

**Comment by TyberiusPrime** [comment]
So my setup.py invocation seems to die with 
an unwrittable install dir (it's in the store...).
Fixing that with --prefix net's me a 
'ValueError: ZIP does not support timestamps before 1980'.

Which I suppose comes form every file in the store being dated 1/1/1970.

Ok, one find & touch to 1980 later:

```
Processing dependencies for dppd==0.22
Searching for wrapt
Reading https://pypi.org/simple/wrapt/
Download error on https://pypi.org/simple/wrapt/: [Errno -3] Temporary failure in name resolution -- Some packages may not be found!
```

but if I'm reading the distutils.patch correctly,
it shouldn't be doing that?

**Comment by bjornfor** [comment]
I think it's the same issue (I also tried --prefix and hit the ZIP timestamp thing), shall we continue the discussion in https://github.com/DavHau/mach-nix/issues/467?
