### ISSUE TITLE
Update pypi-deps-db in flake inputs

### ISSUE THREAD

**Issue by IllustratedMan-code** [DavHau/mach-nix#488]
The current version of pypi-deps-db in the flake.lock file is over 5 months old. 

This should be super quick, `nix flake update` or just manually update the lock file.

**Comment by blissdev** [comment]
Maybe submit a PR? I wonder if this would help with some dependency issues I've been having.

**Comment by IllustratedMan-code** [comment]
@blissdev I made the pull request, but in the meantime if you are having issues with out of date dependencies, here is a sample flake input that should fix the problem.

```nix
  inputs = {
    mach-nix.url = "github:DavHau/mach-nix";
    pypi.url = "github:DavHau/pypi-deps-db";
    pypi.flake = false;
    mach-nix.inputs.pypi-deps-db.follows = "pypi";
  };
```
This just adds the pypi-deps-db input and makes mach-nix follow it.

**Comment by blissdev** [comment]
Thanks!
