### ISSUE TITLE
installable by configuration instead of a command?

### ISSUE THREAD

**Issue by GlassGhost** [DavHau/mach-nix#491]
This project seems well done, is it going to be installable configuration instead of a command?

like for instance if I'm setting up a machine for a set of people, in addition to having to run the command:

`nix-env -if https://github.com/DavHau/mach-nix/tarball/3.5.0 -A mach-nix`

and even then if a new version comes out I will have to keep track of which machine has been updated.

https://search.nixos.org/packages?channel=22.05&from=0&size=50&sort=relevance&type=packages&query=mach-nix

and `nix --extra-experimental-features "nix-command nix" search nixpkgs mach-nix`
returns no results

**Comment by bjornfor** [comment]
(I'm a mach-nix user.)

I guess it depends a bit on your setup, how you want to bootstrap things. I personally inject `mach-nix` in an nixpkgs overlay.

**Comment by bjornfor** [comment]
Well, technically I never _install_ mach-nix -- I only use it with `nix-shell` and `nix-build` in a repo that references nixpkgs + mach-nix via an overlay.
