### ISSUE TITLE
Could not load the Qt platform plugin "xcb"

### ISSUE THREAD

**Issue by JensAc** [DavHau/mach-nix#496]
Hi there, 

I am not really sure, whether this is the correct place to ask, however, I would appreciate any help :slightly_smiling_face: 
I am facing an issue with a pyqt application. You can find the code and the mach-nix environment I built, [here](https://github.com/JensAc/aas_manager). The environment builds fine, but when I run
```
python main.py
```
I get 
```
Got keys from plugin meta data ("xcb")
QFactoryLoader::QFactoryLoader() checking directory path "/nix/store/pjpm6jgl2lzvcbfj169hs1vqzqdy58pl-python3-3.7.12/bin/platforms" ...
Cannot load library /nix/store/8v11dhswxyhm107fw1iimhiq5vblm4r0-qtbase-5.15.3-bin/lib/qt-5.15.3/plugins/platforms/libqxcb.so: (/nix/store/rhj9b0ssrqnhwbbbplslngq9a1dky8a9-gcc-10.3.0-lib/lib/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /nix/store/8v11dhswxyhm107fw1iimhiq5vblm4r0-qtbase-5.15.3-bin/lib/qt-5.15.3/plugins/platforms/../../../../../im7q5f5j9q8x5whs4d2hz9m8il47iidp-qtbase-5.15.3/lib/libQt5XcbQpa.so.5))
QLibraryPrivate::loadPlugin failed on "/nix/store/8v11dhswxyhm107fw1iimhiq5vblm4r0-qtbase-5.15.3-bin/lib/qt-5.15.3/plugins/platforms/libqxcb.so" : "Cannot load library /nix/store/8v11dhswxyhm107fw1iimhiq5vblm4r0-qtbase-5.15.3-bin/lib/qt-5.15.3/plugins/platforms/libqxcb.so: (/nix/store/rhj9b0ssrqnhwbbbplslngq9a1dky8a9-gcc-10.3.0-lib/lib/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /nix/store/8v11dhswxyhm107fw1iimhiq5vblm4r0-qtbase-5.15.3-bin/lib/qt-5.15.3/plugins/platforms/../../../../../im7q5f5j9q8x5whs4d2hz9m8il47iidp-qtbase-5.15.3/lib/libQt5XcbQpa.so.5))"
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "/nix/store/8v11dhswxyhm107fw1iimhiq5vblm4r0-qtbase-5.15.3-bin/lib/qt-5.15.3/plugins" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, xcb, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, webgl.

Aborted (core dumped)
```

I understand that `GLIBCXX_3.4.29` is missing somehow. However, I was not able to resolve that issue so far. I suspect that the issue is caused due to the mismatch in Qt-version for `qtbase==5.15.3` and `pyqt==5.15.4` on nixpkgs, but this is just an educated guess.
Would be great, if someone here could help me out.

**Comment by bjornfor** [comment]
Seems related: https://github.com/NixOS/nixpkgs/issues/115297.

**Comment by JensAc** [comment]
Actually, I tried running the shell with `wrapQtAppsHook`, also. For me that did not seem to work either.

**Comment by bjornfor** [comment]
Can you try https://github.com/NixOS/nixpkgs/issues/168484#issuecomment-1098937528? (For example, export those variables in a shellHook.)

**Comment by JensAc** [comment]
Thanks for the hint, I really appreciate your help :slightly_smiling_face:. Sadly, that did'nt play the trick. 

However, I was able to resolve the issue. The issue was caused due my redundant import of `nixpkgs`. I had 
```
with import <nixpkgs> {};
```
in `shell.nix`, but should, of course, just use `pkgs` as already defined by mach-nix. 
Moreover, I needed to set 
```
QT_XCB_GL_INTEGRATION="none";
```
as also proposed [here](https://github.com/NixOS/nixpkgs/issues/169630#issuecomment-1106344293).
If anyone runs into similar issues, you can check out this commit https://github.com/JensAc/aas_manager/commit/cf07b452b93d7c52bd34d00b3240b99a13f93fdd

**Comment by bjornfor** [comment]
Great!
