### ISSUE TITLE
set current date via mach-nix # date is 01.01.1980

### ISSUE THREAD

**Issue by InLaw** [DavHau/mach-nix#498]
How to give mn-python the current date (of the main OS)?

like:
nix-shell --run "unset SOURCE_DATE_EPOCH; "

**Comment by TyberiusPrime** [comment]
You don't. 
The dates are fixed to 1970/1980 to allow bit wise reproducibility.

**Comment by InLaw** [comment]
I know that dates are issues for reproducibility
never the less after building the mn py env the OS-date should be recognized

**Comment by TyberiusPrime** [comment]
I'm not 100% certain what it is that you're doing.

For me 'nix-shell' leaves SOURCE_DATE_EPOCH set,
while 'nix shell'  doesn't.

Either way, that's not mach-nix' doing.

**Comment by InLaw** [comment]
looks to be a nixos issue 
https://discourse.nixos.org/t/date-time-changes-between-nixos-bash-shell-and-dolphin-shell-tex-compilation-today-vs-01-jan-1980/22183
