### ISSUE TITLE
PyTorch example fails: "not a supported wheel on this platform."

### ISSUE THREAD

**Issue by stites** [DavHau/mach-nix#50]
With a slightly altered version of [Recent PyTorch with nixpkgs dependencies, overlays, and custom python](https://github.com/DavHau/mach-nix/blob/da74d4b31f233fa0a3ab528fb87590fbb75e5157/examples.md#recent-pytorch-with-nixpkgs-dependencies-overlays-and-custom-python) (permalinked), where I add `numpy="wheel";` and use mach-nix's master (currently da74d4b31f233fa0a3ab528fb87590fbb75e5157) I end with the error:

```
ERROR: torch-1.5.0-cp36-cp36m-manylinux1_x86_64.whl is not a supported wheel on this platform.
builder for '/nix/store/af7a21p3sfzzxzdkbmb4vlnrhwixkscy-python3.6-torch-1.5.0.drv' failed with exit code 1
error: build of '/nix/store/af7a21p3sfzzxzdkbmb4vlnrhwixkscy-python3.6-torch-1.5.0.drv' failed
```
I thought it might be an out-of-date pip, so I have tried this configuration with python 3.6, 3.7, 3.8 against torch 1.5.0 and 1.5.1. This always results in the same error.

Originally I tried this on Ubuntu + nix (just torch-1.5.0 and pytorch 3.6), but the full array of testing was on NixOS.

Aside: Very cool project!

**Comment by DavHau** [comment]
From which nixpkgs channel are you picking the python interpreter package which you pass to mach-nix?
Manylinux wheels are supported since 20.03. On earlier versions it will raise exactly that error.

**Comment by stites** [comment]
It was a 19.09+ commit -- great!

**Comment by DavHau** [comment]
Probably mach-nix should raise an error with explanation if an expression is evaluated which is pre 20.03.
