### ISSUE TITLE
Adjust wheel sources?

### ISSUE THREAD

**Issue by stites** [DavHau/mach-nix#51]
> It would be nice to be able to build the torch wheel with GPU support. Ideally, there is a way for this to work in NixOS with the new top-level variables for HPC that has been implemented (mklSupport, cudaSupport) although I am a bit fuzzy on these. However, I think this should be filed as a separate ticket by someone more knowledgable than myself.

The easy way to get cuda support for a torch wheel is probably just by downloading the official wheels from pytorch.org: https://download.pytorch.org/whl/torch_stable.html. I think mach-nix is provisioning its own snapshots of pypi, but would it be possible to adjust wheel sources with one-off links? Ideally in a format which can be managed by [niv](https://github.com/nmattia/niv/)

**Comment by DavHau** [comment]
All the wheel listed on the page you linked should be available via pypi, right? therefore they should be available in mach-nix.
If your package is quite new then you might have to update the deps-db by setting `pypi_deps_db_commit` and `pypi_deps_db_sha256`.
Aside from that, you can always adjust the sources of individual packages by including python overrides via `overrides_pre` or `overrides_post`.

Does this solve you problem?
If not, I'm happy to hear more about your ideas.

**Comment by stites** [comment]
I don't think these are available in pypi -- it looks like pytorch only uploads one version of torch (currently 1.5.1+cu102) -- but it seems like `overrides_pre` and `*_post` is really all I need!

**Comment by DavHau** [comment]
The problem is the cuda stuff won't work with machnix. Mach-nix uses autoPatchelf to patch the binary dependencies of wheels files. Currently only dependencies which are allowed via manylinux1/manylinux2010 specification are patched. Cuda isn't part of it.
So technically pytorch breaks the manylinux specification of python.

We could add some parameter to mach-nix to add additional dependencies to the autoPatchelf routine. If you'd like to do a PR I'm happy to include it.

**Comment by DavHau** [comment]
Actually you can add cuda to the buildInputs of pytorch via overrides_post.

**Comment by DavHau** [comment]
see https://github.com/DavHau/mach-nix/issues/59
and https://github.com/DavHau/mach-nix/issues/103

**Comment by DavHau** [comment]
Few updates concerning this topic:

In the meantime there is the new [override system](https://github.com/DavHau/mach-nix/blob/master/examples.md#using-_-simplified-override-system) which should make it fairly simple to replace the `src` for individual packages.
But of course this doesn't scale well to many packages

Theoretically it shouldn't be too difficult to allow adding extra wheel sources. Give a list of wheel URL's mach-nix could download and scan those wheels to extend it's dependency database on the fly before executing the resolution.
Would this be a benefit for you?

**Comment by DavHau** [comment]
Another solution would be to build a custom wheel package via `mach-nix.buildPythonApplication`. But currently buildPythonApplication doesn't support automatic dependency extraction for wheels. Probably a feature I should add.
