### ISSUE TITLE
dependency from arbitrary URL pointing at tarball

### ISSUE THREAD

**Issue by timm-stelzer-e-farm** [DavHau/mach-nix#515]
Hey there!

First of all, you're doing gods work with mach-nix, thanks so much!

I've run into a problem where I need to integrate https://github.com/explosion/spacy-models, who are releasing the individual models as dedicated tarballs, apparently not addressable by hash (or at least I can't figure out how to do that).

The URLs looks like: "https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.1.0/en_core_web_sm-3.1.0.tar.gz".

Of course, I'm getting an error, if I place that in my `packagesExtra`:

```
error: in pure evaluation mode, 'fetchTarball' requires a 'sha256' argument
```

Is there a way to download those, and if not, a workaround available?

Cheers

**Comment by ryanswrt** [comment]
You can try running your nix commands with `--impure` which will download the tarball; but you might need to fix the mach-nix builds for those manually

**Comment by timm-stelzer-e-farm** [comment]
> You can try running your nix commands with --impure which will download the tarball
I'm unsure how to do that, for context, here's my flake: https://gist.github.com/timm-stelzer-e-farm/f9306293fd472a560bef3a30338f7fc3

I'm using the direnv integration for flakes, I don't know how to make those impure. Apologies, I realize, technically that isn't an issue with mach-nix, but maybe you can still point me the right direction here :) 

> but you might need to fix the mach-nix builds for those manually
How would I do that, if it comes to that? `buildPythonPackage`?
