### ISSUE TITLE
buildPythonPackage fails with "404: Not Found"

### ISSUE THREAD

**Issue by exarkun** [DavHau/mach-nix#535]
using mach-nix bdc97ba6b2ecd045a467b008cff4ae337b6a7a6b and pypi-deps-db 347b6270718ed2191078c852329fd32f04dd34ed building `buildPythonPackage ...` fails:

```
error: unable to download 'https://github.com/DavHau/nix-pypi-fetcher/tarball/9baa976328fe4fc93d89906f92566a5faeedd1a1': HTTP error 404

       response body:

       404: Not Found
(use '--show-trace' to show detailed location information)
```

DavHau suggests the mach-nix code generator may need to be updated to reflect the switch to nix-pypi-fetcher-2 in pypi-deps-db

**Comment by adamlwgriffiths** [comment]
This is currently broken in the latest official release (3.5.0).

```
error: unable to download 'https://github.com/DavHau/nix-pypi-fetcher/tarball/8c1b9cef5570d9d9bfef9eb10920ee5aec712b4c': HTTP error 404
```
