### ISSUE TITLE
Build error when running `mach-nix.mkPython` with `pddlpy` requirement

### ISSUE THREAD

**Issue by peperunas** [DavHau/mach-nix#558]
**Description:**

I encountered a build error when trying to run `mach-nix.mkPython` with the `pddlpy` requirement. The error occurs during the build process of the `antlr4-python3-runtime` dependency.

**Expected behavior:**

The build process should complete successfully, and a Python environment with the `pddlpy` package should be created.

**Actual behavior:**

The build process fails with the following error message:

```
last 10 log lines:
> Using setuptoolsShellHook
> Sourcing pip-install-hook
> Using pipInstallPhase
> Sourcing python-imports-check-hook.sh
> Using pythonImportsCheckPhase
> Sourcing python-namespaces-hook
> unpacking sources
> unpacking source archive /nix/store/3db27jijr6ipp5bkx99i7flr7v6v1i0m-antlr4-python3-runtime-4.9.3.tar.gz
> source root is source/runtime/Python3
> chmod: cannot access 'source/runtime/Python3': No such file or directory
For full logs, run 'nix log /nix/store/y6ih5pyb6cicfvqnxr9icnj8v0h0kcf5-python3.9-antlr4-python3-runtime-4.9.3.drv'.
error: 1 dependencies of derivation '/nix/store/mpaiay49hnjm7nfqj6pbwrsy7q60jqp5-python3-3.9.9-env.drv' failed to build
```

It seems that the build process is unable to find the 'source/runtime/Python3' directory during the unpacking of the source archive.

**Environment:**

- Nixpkgs version: `release-23.05`
- Nix version: `nix (Nix) 2.13.2`

Please let me know if there's any additional information I can provide to help diagnose and resolve this issue.

**Comment by TyberiusPrime** [comment]
Sorry, I have failed to reproduce this.
Do you possibly have a flake showing off the bug?

**Comment by peperunas** [comment]
Sorry for the late reply. I cannot reproduce the bug as well as I am not using the library anymore. I am closing the issue.
