### ISSUE TITLE
When changing default provider getting attribute error

### ISSUE THREAD

**Issue by 573** [DavHau/mach-nix#58]
When I use the `_default` for providers as in

```
providers = {
  _default = "nixpkgs,wheel,sdist";
};
```
my build says:

>copying 1 paths...
copying path '/nix/store/76dsxlbvwn7hk6xwxf2lm3w43m038bzv-mach_nix_file' from 'ssh://builder'...
error: attribute 'unstable-2019-12-09' missing, at /nix/store/js7jvdbqp1i804frs52c7aqsqp0zj7py-nix-pypi-fetcher/default.nix:13:17

**Comment by DavHau** [comment]
It would be great if you could provide a nix expression that causes the error.

**Comment by 573** [comment]
Sure.

I have

```
# ~/.config/nixpkgs/nix-on-droid.nix
{ pkgs, ... }:
{
  home-manager.config = import ./home.nix;
}
```

```
# ~/.config/nixpkgs/home.nix
{ pkgs ? import <nixpkgs> {}, config, lib,...}:
with lib;
let
  home-manager = with pkgs; writeShellScriptBin "home-manager" ''
    # `toString` is required to impurely track your configuration instead of copying it to `/nix/store`
    exec ${(callPackage ./home-sources.nix {}).home-manager}/bin/home-manager -f ${toString ./home.nix} $@
  '';
in
{
  imports = [
    ./program/python
  ];

  home.packages = with pkgs; [
    home-manager
  ];
}
```

as well as [~/.config/nixpkgs/home-sources.nix](http://ix.io/2tj6) and [~/.config/nixpkgs/program/python/default.nix](http://ix.io/2tj7)

It should be possible to have a nix-shell with that configuration using:

```
nix-shell -E "with import <nixpkgs> {}; mkShell { buildInputs = [ (callPackage ~/.config/nixpkgs/home-sources.nix {}).home-manager ]; }" --run "home-manager -f ~/.config/nixpkgs/home.nix switch"
```
