### ISSUE TITLE
Add support for wheels

### ISSUE THREAD

**Issue by DavHau** [DavHau/mach-nix#7]
Since NixOS 20.03, also wheels with binary packages seem to be well supported by nix. See https://github.com/NixOS/nixpkgs/pull/73866.
Using wheels has the following advantages:
1. More libraries can be supported
1. Build times for wheels are much lower than for sdists.

We need to extend [pypi-crawlers](https://github.com/DavHau/pypi-crawlers) to also process wheel releases of the types we are interested in.
See https://github.com/DavHau/pypi-crawlers/issues/3 and https://github.com/DavHau/pypi-crawlers/issues/4

For mach-nix we need to:
 - Find a way to include wheels into dependency resolution process.
 - Adapt the user interface.
 - Extend the overlay generator to be able to generate nixpkgs overlays using wheels

**Comment by RaitoBezarius** [comment]
For the user interface, here's my 2 cents, it should be possible to ask for wheels in priority and fallback on source when not possible. This way, build/install time is minimal.

**Comment by DavHau** [comment]
Wheel support has been added in version 2.0.0
