### ISSUE TITLE
Project installation/setup overview

### ISSUE THREAD

**Issue by InLaw** [DavHau/mach-nix#76]
is there a way to show/ inspect the whole installed setup/packages with versions (and hashes)
regrading 
- linux/OS packages
- language packages for  python c++ js java (which could be related to a package as dependency)

**Comment by DavHau** [comment]
Take a look at https://github.com/utdemir/nix-tree

Does this solve your problem?

**Comment by InLaw** [comment]
(nice and ok for the moment :-)
