### ISSUE TITLE
geopandas / Shapely / pygeos

### ISSUE THREAD

**Issue by InLaw** [DavHau/mach-nix#80]
is there a way to specifiy a certain compiler version for both?

python 
import geopandas 
```
/nix/store/5b38d34wx66pkhn7zx4sn7ias4sgvjrz-python3-3.7.6-env/lib/python3.7/site-packages/geopandas/_compat.py:88: UserWarning: The Shapely GEOS version (3.8.0-CAPI-1.13.1 ) is incompatible with the GEOS version PyGEOS was compiled with (3.8.1-CAPI-1.13.3). Conversions between both will be slow.
  shapely_geos_version, geos_capi_version_string

```

**Comment by DavHau** [comment]
I don't get the error with the newest version of mach-nix:
```nix
let
  mach-nix = import (builtins.fetchGit {
    url = "https://github.com/DavHau/mach-nix/";
    ref = "2.3.0";
  });
in mach-nix.mkPython rec {
  requirements =''
    geopandas
  '';
}
```

Please reopen with nix expression if error still occurs

**Comment by DavHau** [comment]
I just noticed that the error is triggered by the following expression:
```nix
let
  mach-nix = import (builtins.fetchGit {
    url = "https://github.com/DavHau/mach-nix/";
    ref = "2.3.0";
  });
in mach-nix.mkPython rec {
  requirements =''
    geopandas
    shapely
    pygeos
  '';
}
```

**Comment by DavHau** [comment]
The same problem occurs with pip under python 3.8. Tested via `docker run --rm -it python:3.8-slim`.
Please report upstream

**Comment by InLaw** [comment]
how to tell mach-nix the following routine
`pip install --no-binary shapely shapely`

**Comment by DavHau** [comment]
I assume `--no-binary` means that pip will not use wheel releases which include binaries.
For linux those releases would be tagged `manylinux[1|2010|2014]`.

mach-nix does not have such function yet. But you can exclude wheel releases in general by setting `providers.shapely = "sdist,nixpkgs"`

Why do you need that functionality?

**Comment by DavHau** [comment]
I just checkt and shapely seems to not have wheel releases which do not containing binaries.
You can check it here: https://pypi.org/project/Shapely/#files
All .whl releases are platform specific and for that reason can contain binaries.

The only non-binary option is the sdist release.

Therefore the `providers.shapely = "sdist,nixpkgs"` will achieve the same as --no-binary in pip.

**Comment by InLaw** [comment]
one question regarding the date of the pip db 

There is a Shapeky 1.7.1 Aug 21, 2020 but this is not yet in the mach-nix pypi db (even though you updated is two days ago, right?)
- how to figure out about the point in time/date of the pypi db state?

**Comment by InLaw** [comment]
`providers.shapely = "sdist,nixpkgs"`
works :-) thanks again

**Comment by DavHau** [comment]
As you probably already figured out [this file](https://github.com/DavHau/mach-nix/blob/2.3.0/mach_nix/nix/PYPI_DEPS_DB_COMMIT) references the commit of pypi-deps-db, which is currently this one: https://github.com/DavHau/pypi-deps-db/commit/c6c31fb218f67930f3d9200e67a2bff441e38788 from Mon 24 Aug 2020

You can usually assume that the commit date of pypi-deps-db includes a snapshot of everything from pypi from that date, since the crawler runs every 12h.

shapely 1.7.1 is in fact available in the current version of mach-nix. A environment with a single requirement `shapely==1.7.1` resolves successfully.

It might be the case that other requirements in your environment prevent that version via their constraints.

**Comment by InLaw** [comment]
yes, I had to change the rev

**Comment by InLaw** [comment]
What about `blosc==1.9.1`?

```
let
  mach-nix = import (builtins.fetchGit {
    url = "https://github.com/DavHau/mach-nix/";
    #ref = "refs/heads/master";
    rev = "67184df0c2cfe6974b774bc2ca0c10970c9bab39"; 
  });
  py_env = mach-nix.mkPython rec {
    python = mach-nix.nixpkgs.python37;
    requirements =  ''  
    blosc>=1.8.0    
      '';
  };
in
(py_env.override ( args:{ignoreCollisions=true; }) ).env
```
