### ISSUE TITLE
pkgs with issues

### ISSUE THREAD

**Issue by InLaw** [DavHau/mach-nix#84]
jupyter_pivottablejs 
jupyterlab_bokeh  
fastparquet 
orange3 
pymc3 
geoviews
cuspatial 
OSGeo-Easy  
pyModis  
osgeo-manager  
pdf 
pdfminer.six  
perl-pdf-api2 
JCC 
Nikola
blosc
yarn.build

**Comment by DavHau** [comment]
JCC: has non python build dependency. requires jdk to build 
osgeo-manager : depends on ags2sld which is not available on pypi                                    
perl-pdf-api2: doesn't exist on pypi                                      
Nikola: opened ticket (https://github.com/DavHau/mach-nix/issues/91)      
                                                     
### wrong names:                                      
pivottablejs  (not jupyter_pivottablejs)                                        
bokeh          (not jupyterlab_bokeh)                                      
                                                     
### bug fixed (top level deps with dot in name)
pdfminer.six                                       
yarn.build                                         


The rest of the packages build without problem for me. Please re-open if not.

**Comment by InLaw** [comment]
bokeh is the main page
jupyterlab_bokeh is the server for Jupyterlab (for rendering and so on)
and to get the "frontend" you have to install 
- jupyter labextension install jupyterlab_bokeh (which is not the server again)

**Comment by InLaw** [comment]
```
let
   mach-nix = import (builtins.fetchGit {
     url = "https://github.com/DavHau/mach-nix/";
     #ref = "dev";
     ref = "2.2.2";
     rev = "371c0ebf7d6629c6893bc140be541452b2bd3129";
   });

   overlays = []; # some very useful overlays
  pkgs = import <nixpkgs> { config = { allowUnfree = true; }; inherit overlays; };
in mach-nix.mkPythonShell rec {
  python = pkgs.python37;
  requirements =  ''  pymc3  '';
}
```

```
while evaluating 'is_py_module' at /nix/store/hmpr6mlhl59ipkkm4y64hvwjxldxvvya-mach_nix_file/share/mach_nix_file.nix:15:18, called from /nix/store/hmpr6mlhl59ipkkm4y64hvwjxldxvvya-mach_nix_file/share/mach_nix_file.nix:18:20:

error: --- EvalError ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- nix-shell
in file: /nix/store/dzk0krx7hylcm14wcbhpmqw7pi0z6ll3-nixpkgs-20.03.2652.076c67fdea6/nixpkgs/pkgs/development/python-modules/Theano/default.nix (82:35)

attribute 'blas' missing

```

**Comment by InLaw** [comment]
have you checked gdal in 2.2.2 again?
