### ISSUE TITLE
Error: "\u characters in JSON strings are currently not supported"

### ISSUE THREAD

**Issue by DavHau** [DavHau/mach-nix#99]
The following derivation triggers the error:
```nix
let
   mach-nix = import (builtins.fetchGit {
     url = "https://github.com/DavHau/mach-nix/";
     ref = "refs/tags/2.2.2";
   }); #

in mach-nix.mkPython rec {
  python = mach-nix.nixpkgs.python37;
  requirements =  ''
    sphinxcontrib-applehelp
  '';
}
```

**Comment by HaoZeke** [comment]
This seems to be triggered for vanilla `sphinx` as well

**Comment by DavHau** [comment]
BTW, this can be fixed by using a newer version of nix. for example `nix-shell -p nixFlakes`.
Still of course we should fix that issue to support older versions.

**Comment by DavHau** [comment]
This is fixed since a few versions
